### ISSUE TITLE
Naming of Methods / Columns

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#116]
It's come to our attention that so long as we are generating methods that are on the struct that holds the column names, there is a chance for collisions. Here is an example that breaks no matter what tricks we do in the relationship generation:

```sql
CREATE TABLE `alias` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `domain` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `domain_idx` (`domain`),
  CONSTRAINT `alias_domain_domain_domain` FOREIGN KEY (`domain`) REFERENCES `domain` (`domain`)
);

CREATE TABLE `domain` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `aliases` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain` (`domain`)
);
```

You can easily create other collisions by naming things that would originally be taken by our methods, ie: "insert", "find_domain", "upsert" etc.

We see several options:
1. Force SQL Schemas to conform to some sort of "standard" and reject ones that have a bad shape (this hoses people trying to migrate legacy things or use a database in use by another app they can't change)
    **Pros:**
        - SQLBoiler doesn't change from what it does now (within reason)
        - We continue to enjoy a very clean interface, using objects as we'd expect to use them
    **Cons:**
        - We ruin our compatibility with many databases that weren't designed by the conventions set forth by rails / sqlboiler, which is admittedly a lot
1. Try to move the generated methods elsewhere, or name them something impossible to collide with
    **Pros:**
        - Naming collisions become impossible and therefore we will be able to support legacy databases, no matter what convention they used
    **Cons:**
        - The API could become unpleasant to use or at the very least less natural

**Comment by dalu** [comment]
You could say that you'll only support a certain naming convention and postpone a different approach to v3 or an alternate project.
You wrote this tool for you to be useful. And you shared it with the rest of the world.
You can't expect the rest of the world to do things the way you do but you can expect the tool to be used the way you envisioned it. And if it isn't, are you to blame? I don't think so.
It's not like for instance sqlc isn't able to deal with this, or just using the plain driver.
"Use the tool for what it's built for, if you abuse it it's not the tool's fault".

However then you should document which naming convention should be used (if you didn't already).

In this case, a vimbadmin2 schema is deprecated, and they changed the field name in alias to `Domain_id` https://github.com/opensolutions/ViMbAdmin/blob/master/doctrine2/schema-20140211.pdf

I usually use mongodb with the mgo driver.
When I write a "schema" I'm sure to pick appropriate field names.

```
type Alias struct {
ID string `bson:"_id"`
DomainID string `bson:"domain_id"`
}
type Domain struct {
ID string `bson:"_id"
AliasIDs []string `bson:"alias_ids"`
}
```
or rather
```
type Alias struct {
ID string `bson:"_id"`
DomainID string `bson:"domain_id"`
}
type Domain struct {
ID string `bson:"_id"
}
```
but postfix doesn't support mongodb so I'm stuck with sql.
And the truth is I use this because it seems to be the most promising in dealing with already existing schemas. It supports relations, and very well.

Let's sum it up.
A field that is referencing a table should have `_id` suffixed, otherwise it's not a valid schema for this tool.
If it doesn't maybe support it in the next major version or a new project.
At least that's how I'd do it.
Ultimately it's your choice.

**Comment by osleg** [comment]
@aarondl I'm trying to understand how is that happening.
For my case I have schema like
```sql
CREATE TABLE public.agents(
	uid uuid NOT NULL DEFAULT uuid_generate_v1(),
	data_uid uuid,
	is_alive boolean NOT NULL DEFAULT false,
	is_enabled boolean NOT NULL DEFAULT true,
	date_created timestamp DEFAULT ('now'::text)::timestamp without time zone,
	date_updated timestamp DEFAULT ('now'::text)::timestamp without time zone,
	CONSTRAINT agents_pkey PRIMARY KEY (uid)

);
CREATE TABLE public.data(
	uid uuid NOT NULL DEFAULT uuid_generate_v1(),
	agent_uid uuid NOT NULL,
	date_created timestamp DEFAULT ('now'::text)::timestamp without time zone,
	date_updated timestamp DEFAULT ('now'::text)::timestamp without time zone,
	CONSTRAINT data_pkey PRIMARY KEY (uid)
);

ALTER TABLE public.agents ADD CONSTRAINT fk_agents_data FOREIGN KEY (data_uid)
REFERENCES public.data (uid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE public.data ADD CONSTRAINT fk_data_agents FOREIGN KEY (agent_uid)
REFERENCES public.agents (uid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
```

When I run the sqlboil to generate the database I'm getting
```go
type Agent struct {
	UID         string      `boil:"uid" json:"uid" toml:"uid" yaml:"uid"`
	DataUID     null.String `boil:"data_uid" json:"data_uid,omitempty" toml:"data_uid" yaml:"data_uid,omitempty"`
	IsAlive     bool        `boil:"is_alive" json:"is_alive" toml:"is_alive" yaml:"is_alive"`
	IsEnabled   bool        `boil:"is_enabled" json:"is_enabled" toml:"is_enabled" yaml:"is_enabled"`
	DateCreated null.Time   `boil:"date_created" json:"date_created,omitempty" toml:"date_created" yaml:"date_created,omitempty"`
	DateUpdated null.Time   `boil:"date_updated" json:"date_updated,omitempty" toml:"date_updated" yaml:"date_updated,omitempty"`

	R *agentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L agentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// DataUID pointed to by the foreign key.
func (o *Agent) DataUID(exec boil.Executor, mods ...qm.QueryMod) datumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("uid=?", o.DataUID),
	}

	queryMods = append(queryMods, mods...)

	query := Data(exec, queryMods...)
	queries.SetFrom(query.Query, "\"data\"")

	return query
}
```

Is my understanding correct that somewhere in the code you are checking for _id and stripping that off?

**Comment by aarondl** [comment]
That's correct. The fact that we name these columns `_id` (typically) is a convention in the database side, and when considering relationships and reading code, we don't want to see it for these kinds of look-up helper methods.

**Comment by osleg** [comment]
Aye I already looked it up in the code and for my usecase where I have uid instead I just added `_uid` to identifier suffixes.
As of how to do it more flexible I think a good idea would be to add an ability to provide custom suffix to cli command.

**Comment by aarondl** [comment]
I don't think I'll consider that honestly. We use the `_id` convention to prettify names, you don't have to use it if you don't want to (as you've chosen not to) but that's part of sqlboiler's charm. Follow convention and your code will be prettier, deviate and it'll be more painful. As for fields and method names colliding we have fixes coming for that, and I apologize for any duress encountered due to that issue, it's a real pain.

**Comment by osleg** [comment]
I don't think you have to sorry about that :) That's the benefit of being open source, if anyone needs it - he can add it, just like I did :)
I also started the cli config key of adding this but priorities got it delayed :)

**Comment by osleg** [comment]
Also on a side note, as far as I remember from various books, using `id` as field name is discouraged in SQL.
Also the `uid` and `uuid` are very common names in databases which represent `user ID` and `UUID` respectively.

**Comment by aarondl** [comment]
`uid` was perhaps one we shouldn't have done but at the time it was taken as a synonym of `uuid`. `uuid` was intentionally chosen in order to mean `UUID`. Because instead of `id` fields as a primary identifier some people use `uuid` instead. Hence the magic suffix for that as well. Anecdotally there's no database that disallows or breaks (granted I've never used Oracle lol) when using `id` as a primary identifier field, it's always the incrementing integer identifier field. I'm very curious what the source of this discouragement is and the reasoning was if you can provide it.

**Comment by osleg** [comment]
Unfortunately I don't remember which book that was but I do remember it was any database specific book. I remember it was saying that using field name `id` might be an opening for human mistakes.
Tried to google but stumbled upon discussions on the matter, not the book itself. 
Anyhow, that was a "side note" more as a fun fact factor rather something worth to consider since the `id` field is common field in any database I ever met.

**Comment by aarondl** [comment]
The generated Go names for Tables, Columns, and Relationships can now be aliased to prevent collisions: https://github.com/volatiletech/sqlboiler/tree/v3#names
