### ISSUE TITLE
Add `LIKE` and `ILIKE` Operators

### ISSUE THREAD

**Issue by falsaffa** [volatiletech/sqlboiler#1218]
## Overview

Add `LIKE` and `ILIKE` to the set of operators used in `[MODEL]Where.[COLUMN].[OPERATOR]`. Below is a sample of the existing operators supported including: `EQ`, `GTE`, `GT`, `IN`, `LT`, `LTE`, `NEQ`, `NIN`.

<img width="804" alt="Screenshot 2022-10-30 at 10 25 20 PM" src="https://user-images.githubusercontent.com/44938179/198924749-929b91aa-4ede-4d37-bf2b-895501a2d2a8.png">

With the `LIKE` and `ILIKE` operator, the following:

```go
qm.Where(gen_models.ProductTableColumns.Name+" ilike ?", queryTarget),
```

turns into:

```go
gen_models.ProductTableColumns.Name.ILIKE(productID.String())
```

I may be alone in this, but I use the `LIKE` and `ILIKE` operators readily enough that having shorthand would be useful.

## BTW

Absolutely love sqlboiler. I wish I knew of it early! ❤️

**Comment by stephenafamo** [comment]
Officially, SQLBoiler supports 4 dialects.

* Postgres
* MySQL
* SQL Server
* SQLite

To add `LIKE` and `ILIKE`, they have to be operators in all 4 dialects. Alternatively, we could add some check to make sure the dialect supports it before generating the code for the operators, but that will not be as straightforward.

**Comment by falsaffa** [comment]
If I were to open a PR using the code generation method (check the dialect before adding the enum) would that be an implementation you would be happy to review/approve?

**Comment by stephenafamo** [comment]
Yes. Alternatively, you can add it under the driver templates, the same way dialect-specific code for Upserts are generated.

**Comment by falsaffa** [comment]
So played with it a bit and I have a couple questions:
- `qmhelper` is it intended to be widly used outside of sqlboiler code? Considered adding `ILIKE` and `LIKE` operator, but since they aren't supported for all dialects it may seem deceptive to include?
- `LIKE` is a common operator across the dialects, so that makes sense to include in the core templates. However, `ILIKE` is unique to postgres. I thought of just including it in the core template only if the driver given is postgres, but how strongly are your thoughts in having it be a separate template file in postgres? (only postgres since it's the only driver that supports it)

**Comment by stephenafamo** [comment]
- I think a separate template file is best for any driver-specific template. This is their intended purpose.
- I don't think `LIKE` and `ILIKE` should be added to `qmhelper`. Instead, the generated code can use `qm.Where(...)`

**Comment by stephenafamo** [comment]
@jerrysalonen 

> Are issues considered "taken" or is anyone free to go for a PR?

Feel free to send a PR. Considering this is over 6 months old, it is likely that if someone was working on it, it has been sidetracked by some other life event. This is all free work 😁 



> Do you mind where in the generated file the `LIKE`, `NOT LIKE` etc go or is it ok to just drop it at the end of the file where all the other `whereHelperstring` methods get generated? As I understand it, having it elsewhere would result in a bunch of file renames, right?

I do think it belongs close to the other where helpers. Although, you should not these operators are not present in all the dialects so it has to be in a dialect-specific template, in which case it may have to be included with a `{{block}}` to place it in the right place.  
However, if the way the templates are loaded and executed is hard to understand, you can create them in a dialect-specific way similar to how `upserts` are done, and I can move them around.

> I tried to look around and did not find tests for the other operators – should tests be written for these if I were to make a PR for this?

Tests are welcome. Because of how complicated it is to test generated code that could be subject to all sorts of database schemas, we've not been paying much attention to the tests, but please add some if you can.

> And finally: I was thinking about having `ILIKE` available for all dialects in some form even if not natively supported. Do you think it would be ok to implement `ILIKE` code for those cases with something like
>   ```go
>   qm.Where(fmt.Sprintf("LOWER(%s) LIKE LOWER(?)", w.field), x)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ...or rather not have `ILIKE` at all if the dialect does not support it? Using the `LOWER` might mess with index search so I am not entirely happy with this solution, thoughts? As far as I can tell, `LIKE` is supported in all supported dialects


I don't like the idea of simulating support for something that is not natively supported. Leads to all sorts of unexpected things down the road. Best to stick to what the dialect allows.
