### ISSUE TITLE
when insert a model uses timestamp without timezone, insert return value(boiler object) may be different.

### ISSUE THREAD

**Issue by Limm-jk** [volatiletech/sqlboiler#1231]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.13.0

### What is your database and version (eg. Postgresql 10)
Postgresql 14

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

When using the column using timestamp without timezone as the type and performing the insert operation, I found that the value of db and the value of the boiler object were different.

I found that this was caused by discarding the timezone when saving the time.Time value containing the timezone internally. And I found out that this column was not specified as returnColumn, so it was not updated.

Please let me know if you know how to solve this problem. (except reload)
And I think it would be nice if these parts were written in ReadMe.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE test_timestamp (
  timestamp_without_timezone timestamp,
  timestamp_with_timezone timestamptz
);
```

**Comment by stephenafamo** [comment]
In general, SQLBoiler assumes that any field inserted does not have to be returned since it is the same value. 

You will need to reload the model. Alternatively, you can manually build the insert query with a `RETURNING *` and bind that to the model.

```go
var pilot models.Pilot
err := queries.Raw("INSERT INTO ... RETURNING *").Bind(ctx, db, &pilot)
```

Changing the current behaviour will be quite costly, and backward incompatible for little benefit. So I will close this issue as a "won't fix".
