### ISSUE TITLE
Failing tests on ToMany relations while working with enums

### ISSUE THREAD

**Issue by tarnowsc** [volatiletech/sqlboiler#179]
I'm having trouble with SQLBoiler v2.5.0, working with postgres. This is my db schema:
```sql
CREATE TYPE user_role AS ENUM (
    'user',
    'admin'
);
CREATE TABLE users (
    id uuid NOT NULL,
    email text NOT NULL,
    password_digest text NOT NULL,
    created_at timestamp with time zone
);
CREATE TABLE users_roles (
    user_id uuid NOT NULL,
    user_role user_role NOT NULL
);
ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, user_role);
ALTER TABLE ONLY users_roles
    ADD CONSTRAINT users_roles_users_fk FOREIGN KEY (user_id) REFERENCES users(id);
```
While running generated tests, I'm getting failures on relations:
```bash
go test ./models/
--- FAIL: TestToMany (0.00s)
    --- FAIL: TestToMany/UserToUsersRoles (0.00s)
    	users_test.go:492: models: unable to insert into users_roles: pq: duplicate key value violates unique constraint "users_roles_pkey"
--- FAIL: TestToManyAdd (0.00s)
    --- FAIL: TestToManyAdd/UserToUsersRoles (0.00s)
    	users_test.go:576: failed to update foreign table: pq: duplicate key value violates unique constraint "users_roles_pkey"
FAIL
FAIL	main/models	2.203s
```
Tests on **Users** relation to **UsersRoles** violates the uniqueness of primary key on users_roles table. Probably the entropy of enum is too low to avoid the collision. While extending the enum by new values the probability of fail decreases, nevertheless that is not a solution.

**Comment by aarondl** [comment]
Hey there @tarnowsc, sorry I didn't get back to you sooner I was on vacation.

I'll have to look into this one in more detail to see exactly the cause. Thanks for filing the issue.

**Comment by aarondl** [comment]
Hey @tarnowsc, so I looked into this issue and can solve one of the errors with a fix to the randomize package that should have always been in there. However one of the tests assumes that it can always insert four associated values in order to test the given functionality. There's actually no ability to fix that without sacrificing some of the integrity of the test, since it wants to deal in multples (these are set operations after all, and we don't want to assume that behavior for n will be the same behavior for 1). But even then it'd only work for enums with length 2, and it's possible to have an enum of length 1.

I'm unclear on what else we can do at this moment. It seems like if we don't slim down the relationship set helper tests, there's no way we can have a database like this fully pass.
I'm open to ideas, but I think maybe the best thing is to simply skip the remaining test. You'd probably have to sed the line in the `boil_suites_test.go`
you can find the line to remove like so: `ag 't.Run.*testUserToManyAddOpUsersRoles' ./models/`

Are you okay with this solution? I wish I could do better and like I said I'm opened to other ideas.

**Comment by tarnowsc** [comment]
Hi @aarondl , sorry for late response I was also on vacation. I've solved this by turning off those tests and was hoping for some bright idea, but as you wrote there is no easy fix.

**Comment by aarondl** [comment]
Let me just keep this one opened. There is at least one bug here that fixes one of the issues. Will fix that.

**Comment by taka41s** [comment]
soo any fix for this? I'm facing this right now
