### ISSUE TITLE
Support for CockroachDB?

### ISSUE THREAD

**Issue by dtrinh100** [volatiletech/sqlboiler#187]
Is it possible to use CockroachDB with sqlboiler? CockroachDB uses the postgres driver, but I am not sure if that means I can use it with everything that supports Postgres. If not, are there any plans in the future to add support for CockroachDB?

**Comment by aarondl** [comment]
There are no plans for any future databases except those that others submit like the sqlite3 PR that's currently opened.

I think that trying to masquerade cockroachdb as postgres would work for actually generating and running (you can try this, it's not hard). But the generated tests will fail since they shell out to postgres' command line tools.
