### ISSUE TITLE
ModelBase versus Model

### ISSUE THREAD

**Issue by alsonkemp** [volatiletech/sqlboiler#223]
When I did something similar in Haskell, my code generated something like /models/User.go and /models/UserBase.go.  User.go was generated initially if it was missing then was never overwritten.  All the overwriting went into UserBase.go, User.go imported and re-exported.  This allowed us to add utility methods and such to User.go.

I'm not Go expert but, if you think it sounds interesting, I could try doing this for sqlboiler.  Thoughts?

**Comment by aarondl** [comment]
I've done some Haskell myself! Fun language, I like functional.

In the past we've had this discussion and it's ended in a best practice documented in the readme:
https://github.com/volatiletech/sqlboiler#extending-generated-models
I'd say sticking to these is best. To me there's no downsides to the first model other than maybe a little more verbosity than we'd all like.

One of the biggest reasons for this is largely philosophical; I hold the opinion that hand-written code should never be shoved away inside
a directory full of 99% generated code. It's hard to understand where one stops and the other begins. It's especially bad because Go's package
model means folder == package. So `models.HelpMe` <- Is this yours? Or is it sqlboilers? Are you allowed to modify it? All impossible with
this approach when reading the code unless you go look at what file the function is in, which seems like a burden put on the reader.

It's also not clear what advantages this approach provides over the best practices that are documented. I'm opened to having more discussion about it,
but will close this issue for now :)

**Comment by alsonkemp** [comment]
@aarondl At the risk of sounding as if I'm bikeshedding (I'm not!):

Thanks for your quick response.  Definitely a good point about mixing auto-gen-ed code with user-generated code and I totally agree.  I had forgotten but I actually did that in my Haskell version of PG code-gen: https://github.com/alsonkemp/turbinado-website/tree/master/App/Models

I read the best practice link you sent.  I tend to lightly extend models and then compose/manage them via "services".  My challenge with "modext" is that it's not clear where the responsibilities begin and end between modext and models.  For example, I would expect my User *model* to have an encryptPassword method on beforeSave (or similar) but that appears to be relegated to a *modext* file; at the same time, I would expect modext.User.login to create Login records but that's more of a service-y, coordinate-models thing so doesn't seem to belong in modext with the little encryptPassword function.

Perhaps for a future major release, code-gen could be clearly separated out:

    /models/User.go - extendable stub of the code-gen code; here lives encryptPassword()
    /models/generated/User.go - SQLBoiled goodness
    /services/User.go - login() lives, creation of Login records, etc live here; not code-gen-ed

In the above, I clearly can extend /models/User.go and should not touch /models/generated/User.go.  

Semantics do matter (after all, my confusion and this ticket are due to them).  I realize I'm suggesting a breaking-ish change.  I'll fork SQLBoiler and work on teaching myself Go as I push the codebase in the above direction.  The worst that happens is that I increase my knowledge Go.  That said, if the above is interesting, I can add detection&upgrade logic so that the change is seamless to users.  Thereafter, the best practice could be: use /models/User.go to your heart's delight but don't touch the /generated/ one!

I've been frustrated at the state of Go's ORMs and think SQLBoiler is on the right track so thanks for the effort and the consideration.

**Comment by aarondl** [comment]
No bikeshedding detected at all! The interesting thing is we're saying the same thing from my perspective with one tiny exception.

`modext` is just a best practice. It's a name of a package that's short and won't be taken by the user generally speaking. You could name it whatever you like. This is exactly the same as your `/models/User.go` file with the exception that it's not generated by `sqlboiler` and you write functions like so:

```go
func encryptPassword(u *User) {...}
```

and not:

```go
func (u *User) encryptPassword { ... }
```

And then `/models/generated/User.go` is simply `/models/User.go` in the current world. Services can be put anywhere, but neither `modext` nor `models` seems like the best place for it, so that's an exercise for the user.

In terms of semantics, you simply never touch `models` which to me is very clear. `modext` is a user-created package, you make it, you put functions in it, and you maintain it. No stubs are required to be generated for this because everything should be doable from outside the models package. We have hooks available for workflow pieces when required (in the example of the `encryptPassword` piece). Everything else is exported and you can manipulate it directly.

Maybe that clears some things up?
