### ISSUE TITLE
Bad function design `Exec()`

### ISSUE THREAD

**Issue by xahon** [volatiletech/sqlboiler#242]
I think `func (c *SQLiteConn) exec(ctx context.Context, query string, args []namedValue) (driver.Result, error)` has bad design.

```Go
Raw(db, "--
SELECT something_useful FROM bbbb WHERE (user_id = $1);
INSERT INTO user_comments (user_id, comment_id)
   SELECT $2, id FROM comments WHERE (date = $1);", 
UserId, CommentDate)
```

This example will fail because `exec` function splices args array each sql command separated by `;`  
To make it work you need to pass `UserId, UserId, CommentDate` parameters and so on if it will has more queries.  
I think it's designed bad because `$` placeholder is indexable and there's no reason to splice array unlike `?` placeholder

**Comment by aarondl** [comment]
Unfortunately we're stuck with the lowest common denominator when it comes to databases. This is a problem because MySQL, MSSQL and SQLite exist. They don't support the functionality you're after, and so we cannot support it (easily). I don't think we'll change this. It also hurts the ability to switch databases later on.
