### ISSUE TITLE
Recommended approach to expose models without R field

### ISSUE THREAD

**Issue by roobre** [volatiletech/sqlboiler#272]
Hi there,

I'm currently testing sqlboiler for a project, and it seems to work really nice!

However, I'm kind of facing a problem with exposing data to the outside (JSON REST API), as SQLBoiler generates models with relations under a field called `R`. This is not desirable when exposing data, so it should be translated somehow. I'm not sure which would be the desired approach, as hand-writing my own models with constructors using sqlboiler's models as parameters seems like a pain and bad design to me. Is there a solution to achieve this in a more reusable way?

Regards and thanks in advance for your time.

**Comment by aarondl** [comment]
Hey there,

It wasn't ever really the plan for sqlboiler models to be able to be thrust out on to the internet via JSON marshalling.

You'll notice that the models are generated like this:

```text
	R *antR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L antL  `boil:"-" json:"-" toml:"-" yaml:"-"`
```

Which basically disables them from having relationships etc. marshalled as JSON. If you'd like relationships (ie you're trying to make graphql handlers or something) I'd recommend some simple wrapper structs to package your data. You can make them inline and they'll be small since they'll only be pointing to defined structs already. Does that solve the problem?

**Comment by aarondl** [comment]
So a wholesale reimplementation is not required. As you can see here:
https://play.golang.org/p/7B1id3iWUaD

What is required is a definition of the relationships between them, which I think is mostly fine since I think most API responses will not contain JUST a model anyway, so you'll have this response struct anyhow and it becomes trivial to add whatever you'd like to it in whatever way you would like.

The only reason `R` is not exposed, is because of it's name that you can't change, the fact that it'd betray the stack you were using for your API (sqlboiler) which is a very bad thing on the internet, and at the time for some reason I thought that people would not want these related items being thrown out there, as if it were a leak. It's possible we could reconsider this if enough people think that it'd be better to expose it. We could possibly do something where if you renamed R, it's exposed, if not, it's not. Renaming R might not be as easy as I think though, since I think it's presence on the structs gets deep inside the eager loading stuff, but yeah... Something to think about.

We've already traveled down the path of "some files won't be deleted" in the directory in a previous discussion and I've decided that's not going to be the way to go. The directory is meant to be a "I can delete this at any moment and be safe". I don't want to start mixing user code and generated code in that folder as a matter of principle.

You can override the templates wholesale if you want by using `--basedir` and add whatever functions you want as one method.

There's also other ways to extend your models documented here:
https://github.com/volatiletech/sqlboiler#extending-generated-models

**Comment by roobre** [comment]
Hi there,

Thank you so much for the detailed response. I was indeed thinking about something on the lines of what your playground code does. It is true that "rest-friendly" models are easy and cheap to create (it would be zero-copy if you embed pointers instead), but it is still a task which must be done by hand. On the other hand, you're right when you say that mixing generated code and user code in the same package can lead to difficult to mantain situations.

Probably exposing `R` directly is a bad idea, as it would encourage users to just output that over json, which is neither good practice nor how json is supposed to work. I wonder, why did you choose to have a field named `R` instead of embedding it? Or maybe just adding related models as fields directly? I'm sure these approaches have their own disadvantages, of course. I'm just asking out of curiosity.

Anyway, I'll probably go with the embedding approach. I don't like writing boilerplate, but sometimes it's just something that needs to be done. Thanks again for your time and effort!

**Comment by aarondl** [comment]
Embedding the relationship structs instead of using R would have led to a lot of pain whenever someone went to get field code completion in an editor. You type: `model.` and you see fields for half the models in your database (since those models in turn have other embedded things). If you meant instead of embedding why didn't I just have a struct field for each relationship? That's a better question. I suppose it was an arbitrary organization decision, that it would somehow be easier if you knew that everything under `R` was magically brought into your app.

I'm going to close this issue (just pruning today), thanks for the discussion. Given your previous message I'm understanding that you've come to a solution so there's nothing more to be done here.

**Comment by arjendevos** [comment]
For people who don't want to do this manually: https://github.com/expanse-agency/sqlboiler-erg
