### ISSUE TITLE
how to scan table and parse to struct

### ISSUE THREAD

**Issue by gensmusic** [volatiletech/sqlboiler#294]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v2.6.0

### Further information. What did you do, what did you expect?
Currently I scan table by 

	rows := AccountsG().QueryP()
	for rows.Next() {
		var act Account
		if err := rows.Scan(
			&act.ID,
			&act.GUID,
                        .... a lot of columns here !!!
         	); err != nil {
			fmt.Println("scan got err", err)
			continue
		}
              fmt.Println(act)
        }

Is there any built-in function to build to the struct ???

**Comment by ceshihao** [comment]
Please refer to https://github.com/volatiletech/sqlboiler#select

Use `.One()` or `.All()`

**Comment by aarondl** [comment]
See above comment. Thanks for jumping in @ceshihao :)

In addition to that, see the section on finishers in general which shows you all the ways you can "end" a query:
https://github.com/volatiletech/sqlboiler#finishers

**Comment by gensmusic** [comment]
Sorry I didn't make myself clear. I mean, how to iterate a talbe with size like 1000000000 and scan data to struct.
I don't think I can use All() in this case.

**Comment by aarondl** [comment]
Oh wow haha. Yeah that's a *very* different question. So I looked at the code a bit to see if that would work, but unfortunately [`Bind(rows *sql.Rows, obj interface{})`](https://github.com/volatiletech/sqlboiler/blob/master/queries/reflect.go#L85) which is what would normally help you do this [consumes all the `*sql.Rows`](https://github.com/volatiletech/sqlboiler/blob/master/queries/reflect.go#L224) even if it's only scanning one object. Really it should break after it's descended into here: [here](https://github.com/volatiletech/sqlboiler/blob/master/queries/reflect.go#L230).

I've corrected this on both dev and v3 branches, however neither of those are technically released yet, but dev is pretty stable right now since all our efforts are on v3 so I have no problem saying you could use the dev branch.

Having said that the performance of calling `Bind` over and over like that will actually be worse than hand crafting because there are a number of duplicated actions each call:
1. It determines if your struct is a slice, slice of pointers, or struct.
1. Columns are fetched from `*sql.Rows`
1. Mapping is fetched from cache (created on the first time through)

Columns isn't going to change after every `Next()` and the mapping is always going to be the same. So if you need raw performance I suggest you mirror the bind call [here](https://github.com/volatiletech/sqlboiler/blob/master/queries/reflect.go#L175) by doing the following:
1. Get the columns from the `*sql.Rows`
1. Make a struct mapping using `MakeStructMapping` (this maps all of your column names to paths to pointers)
1. Make a bind mapping using `BindMapping` (this maps all of the columns you care about (ie. the columns from the sql.Rows) to paths to pointers)
1. Use `PtrsFromMapping` on your object to retrieve the pointers for the struct to scan into.

But of course you may want to benchmark to see if you care that much about the performance implications first :)

**Comment by gensmusic** [comment]
Thank you very much for your answer. It helps a lot.
I love you guys.
