### ISSUE TITLE
Executable file not found.

### ISSUE THREAD

**Issue by vevsatechnologies** [volatiletech/sqlboiler#320]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
shows: sqlboiler command not found.

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
go generate

**Comment by aarondl** [comment]
sqlboiler doesn't appear to be installed correctly (is $GOPATH/bin in your path?).

go generate is a dumb command that will attempt to run whatever you put in your go generate statement. If you can't run the same command in your terminal first successfully, there's no point to try go generate.

This isn't a very good bug report by the way since it's very difficult to understand what problem you're experiencing and what your expectations are.
