### ISSUE TITLE
Using indexed parameters with `sqlserver` driver

### ISSUE THREAD

**Issue by nadilas** [volatiletech/sqlboiler#331]
Syntax for indexed parameters with driver: `sqlserver` when using https://github.com/denisenkom/go-mssqldb has to be changed from `$n` to `@pn` in order for queries (generated via `query_builders#BuildQuery`) to work.

Upon changing the following line, the queries are filled:
query_builders.go:493
```go
paramBuf.WriteString(clause[:paramIndex] + fmt.Sprintf("@p%d", startAt)) // previous format: "$%d"
```
Without digging through the whole lib, the following line should also be changed:
strmangle.go:477
```go
buf.WriteString(fmt.Sprintf("@p%d", start+i)) // previous format: "$%d"
```

I think the best way to overcome this would be a global config similar to `boil.SetDb()` just for the driver. Although if the driver can be detected on the fly without configuration, even better.

Let me know what you think.

**Comment by aarondl** [comment]
BuildQuery works if you pass mssql as the driver name instead of sqlserver

**Comment by aarondl** [comment]
The global config is not the place for this. If anything it would go in the SQL dialect which already stores info about a driver like what kind of quotes it uses. The hard thing about this is retrofitting the strmangle package to deal with this. It's a medium amount of work.

I'm also personally not interested in supporting mssql outside the bare minimum. If it limps I'm okay with this. It was all contributed by an outside contributor whose now gone and who left me with a maintenance burden for a platform I don't use or want to use in the future.

So additional features or improving it is left up to outside contributions. If you're interested in making this change I can help steer and get the breaking changes done now so that we can work on this outside the v3 time lines.

I'll obviously continue to help fix your bugs in the mssql code in the meantime. Back to work soon ish.

**Comment by nadilas** [comment]
Fair enough. Changing to mssql solved the issue.
