### ISSUE TITLE
Accessing sql driver specific error

### ISSUE THREAD

**Issue by tcr-ableton** [volatiletech/sqlboiler#335]
Hi, 

I'd like to know if there is anyway I can access the underlying sql driver (postgres in my case) errors from the generated models? I'm especially interested in accessing the error code.

My use case is the following: I'm building a Rest API and I want to return a 409 Conflict when a user tries to create a resource that already exists. To do that I currently have to do two requests: first a request to check if the resource already exists, and then a second one to insert it if it's not.

Even though the result of the exists query will probably be cached most of the times, it clutters my codebase with unnecessary code; and I'd rather like to be able to access the error codes that the [`pq` sql driver attaches to errors instead](https://github.com/lib/pq/blob/master/error.go), so I can take higher level decisions based on my sql `insert` request. 

Cheers!

**Comment by aarondl** [comment]
We use the github.com/pkg/errors library. You should be able to use the cause function:
https://godoc.org/github.com/pkg/errors#Cause

If this doesn't work re-open because that means we've missed using the errors package somewhere.

**Comment by tcr-ableton** [comment]
Hey @aarondl thanks for the quick answer,

that's unfortunately not what I was looking for. `errors.Cause` basically unwraps the error message that sqlboiler wraps from the models. I'd be interested in accessing the actual [Error](https://github.com/lib/pq/blob/master/error.go#L25) object that lib `pq` generates, so I can access the error code and act accordingly.

**Comment by aarondl** [comment]
```
func Cause(err error) error
```

This is the function signature of the cause method. It unwraps the error itself to the original error that started the chain.

I verified the code and am almost certain that if you call `errors.Cause` with the error returned from Insert you will be left with the error that was given to us from the `database/sql` interface which comes from the pq driver. You need to type assert the error returned from `errors.Cause` into the pq `Error` type in order to get what you want.

```go
err := user.Insert(...)
if err != nil {
  e := errors.Cause(err)
  pqe := e.(pq.Error)
}
```

Something like the above.

**Comment by tcr-ableton** [comment]
It works indeed, thanks a lot for pointing that out!
