### ISSUE TITLE
TLS Handshake Issue

### ISSUE THREAD

**Issue by Iukekini** [volatiletech/sqlboiler#350]
SQLBoiler v 2.7.3

"go generate" was the command.  I am connecting to a mssql db in azure.

Command failed to run and produced the following error. 
Error: unable to initialize tables: unable to fetch table data: unable to get table names: TLS Handshake failed: Cannot read handshake packet: EOF

**Comment by aarondl** [comment]
Hey there, firstly I'd recommend moving to version 3 if you can (especially if you're just starting with sqlboiler) as it says in the README.

Secondly there's not much I can do to help with this other than to recommend to check out how you would normally connect to the database using Go.
The sqlboiler-mssql driver doesn't do anything too fancy: https://github.com/volatiletech/sqlboiler/blob/v3/drivers/sqlboiler-mssql/driver/mssql.go#L111

Due to the nature of the error I'd also tell you to try toggling the SSL by using the following bit in your config.

```toml
[mssql]
sslmode="disable"
```

**Comment by Iukekini** [comment]
Thanks, removed the  sslmode="disable"  to enable ssl and everything worked.
