### ISSUE TITLE
One to many where clause

### ISSUE THREAD

**Issue by liepaja** [volatiletech/sqlboiler#363]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
 v3.0.0-rc10

### Shema

> CREATE TABLE users (
>   id SERIAL PRIMARY KEY,
>   name_id INTEGER REFERENCES names(id) NOT NULL,
>   guid VARCHAR(50) NOT NULL,
>   provider provider NOT NULL,
>   email VARCHAR(80) NOT NULL,
>   type user_type NOT NULL
> );

> CREATE TABLE phones (
>   id SERIAL PRIMARY KEY,
>   user_id INTEGER REFERENCES users(id) NOT NULL,
>   number VARCHAR(50) NOT NULL,
>   country_code VARCHAR(50) NOT NULL
> );

There is a one to many (user to phones) relationship. How would the request look like?
I have tried:
`user, err := models.Users(qm.Where("R.Phones.number = ?", "+532532")).OneG(context.Background())`

`user, err := models.Users(qm.Where("Phones.number = ?", "+532532")).OneG(context.Background())`

**Comment by liepaja** [comment]
The solution is eager loading like this:
`user, err := models.Users(qm.Load("Phones", qm.Where("number = ?", "+432432432")),).OneG(context.Background())`

**Comment by liepaja** [comment]
Actually i doesn't work, it doesn't do the where clause. Any ideas how to accomplish this?

**Comment by aarondl** [comment]
The syntax you suggested does the following: Select a user (just randomly the first one in the database, because you're using `One`), and then load all of his phones where the phone number is what you've passed in (which is of course just one phone). Just looking at a query like this it seems extremely unlikely that this is what you want (a basically random user? But you're looking at the same time for a specific phone number on that random user?). It's much more likely that you want to find the phone and load the user for it.

```go
phone, err := models.Phones(qm.Where("number = ?", "+43343434"), qm.Load("User")).OneG(context.Background())

// The user that the phone belongs to will be in:
// phone.R.User
```

Looking at your bug report, it's difficult to tell if sqlboiler isn't doing what you want and there's a bug, or if the query you constructed isn't doing what you want and you just need to adjust your query to make more sense. Please describe the problem you're trying to solve a little better, or if there's a bug present: what you expect to see, and what you actually see.

**Comment by aarondl** [comment]
Also worth noting that I think this also works and is better since it uses inner join, not an eager load, as eager load does two queries, and the inner join would do one.

```go
user, err := models.Users(qm.InnerJoin("phones on users.id = phones.user_id"), qm.Where("phones.number = ?", "+2424242")).One()
```
