### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alishaagupta** [volatiletech/sqlboiler#369]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### Further information. What did you do, what did you expect?
I am fetching json data from an api and storing it in a db . USing the insertion query on the db shows this error. Only frst row is being inserted . I am using a for loop for the whole data, but it shows the error.

**Comment by aarondl** [comment]
Hey @alishaagupta. This kind of a bug report is really unhelpful :(

I have no idea what could possibly be going on because there's no code to look at, there's no stack trace, there's no way with this little information I can know whether it's your code or something in sqlboiler causing the problem. It's simply insufficient for me to be able to do anything. You'll have to put in more effort into the bug report for me to be able to help.

See all the bold text from the bug report template? These are questions that help you provide relevant details. Leaving out the sqlboiler version for example is immediately detrimental. Try to fill in as many of these details as possible.

Also try to imagine that you are the maintainer of sqlboiler, then imagine what details you would need to fix the bug you've encountered and provide those in a new bug report. I'm closing this one as it's simply insufficient. Sorry!
