### ISSUE TITLE
how to use global hooks?

### ISSUE THREAD

**Issue by sirmadboy** [volatiletech/sqlboiler#380]
Hi, thank you for your great work. 
I like to know is there any way to add model hook globally? I have uuid column in every table and I like to generate uuid for every data are inserted.

**Comment by Dexus** [comment]
See: https://github.com/volatiletech/sqlboiler/issues/377#issuecomment-415648355

**Comment by aarondl** [comment]
@sirmadboy There is no way to globally set hooks currently. This is because hook functions don't pass `interface{}`, they pass your actual model so you don't have to typecast it etc.

You can still write a generic function using `interface{}` to apply the change, but you'll have to call it in a function you create for each model.

**Comment by ctrlx-altf4** [comment]
Hi @aarondl 

I don't understand the usage of hooks if they are to be set in each function. I mean I could simply write the logic without using any hooks before performing any other operations instead of setting hooks. It only makes sense if hooks could be set globally.

Will you please help me understand the use case of hooks?

Thank you for this amazing library.

**Comment by ctrlx-altf4** [comment]
Hi @stephenafamo  thank you for replying.

Can you give me an example of where I need to define the hooks for every model? I tried creating hooks within the main function but it didn't work.

**Comment by stephenafamo** [comment]
@ctrlx-altf4  from the README

```go
// Define my hook function
func myHook(ctx context.Context, exec boil.ContextExecutor, p *Pilot) error {
  // Do stuff
  return nil
}

// Register my before insert hook for pilots
models.AddPilotHook(boil.BeforeInsertHook, myHook)
```

Whenever this is run, it will register this function to be run before any insert of a Pilot model. To avoid duplication you may wrap the hook registration in a `sync.Once`.
