### ISSUE TITLE
Move project to Go modules

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#382]
Are there plans to add a `go.mod` to the project? Maybe when the feature stops being not experimental?

**Comment by aarondl** [comment]
Absolutely! In fact I already tried it in a local branch. However there are a few barriers and reasons to put it off.

1. Go modules is a horribly buggy feature at the moment. I say this with as much love as possible, I quite like the modules feature.
    https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Amodules
    I would like to see some of these bugs cleaned up before we start telling people to use Go modules with `sqlboiler`.

2. Right now there's still many Go versions (afaik <1.10.4 and <1.9.7, and yes I know 1.9 is deprecated but lots of people are still using it) in the wild that will not build the project correctly if they see semantic import versioning. This literally breaks users irreparably (outside forking or rollbacks) and is one of the biggest problems with the modules implementation as it stands. And you might say "well just add a go.mod file and don't do semantic import versioning" but that's a non-starter as you cannot opt out of semantic import versioning. If your project has a `go.mod` you must use SIV or it breaks.

3. One of the reasons to put this off is because Go modules will actually work fine with `sqlboiler` as is. For libraries that are >v2 that do not have a `go.mod` file, it gets pulled in as `v3.2.1+incompatible`. This tells Go that it's an old library (no SIV or `go.mod`) but still allows you to manage versions with go modules. This is the best of both worlds for now: No breaking slightly older Go version users, and users who are using modules get some of the benefits. The missing benefits being of course being that nobody knows what versions of it's dependencies it needs. But that's the world we lived in pre-modules anyway and it's been working for quite some time, we can afford to move a little slower so we don't break things.

I think because of 1, I'd like to hold off for a while, given that 3 allows people using modules with at least a small amount of benefit. One day we will definitely migrate to SIV + `go.mod` but I don't think today is the day.

Leaving this opened for other people to see/contribute to the conversation.

**Comment by ccpost** [comment]
To add to (3) above a little bit: I'm currently on v2, and would *really* love to upgrade to v3, but keep having to put it off since it'd be a sweeping change across the entire codebase.  It seems with the Go modules "incompatible" way of doing this, there isn't any way to leverage semantic import versioning in Go modules such that I could have both versions of the sqlboiler models co-exist in the same codebase and do an incremental rather than wholesale upgrade.

Being able to easily migrate through breaking changes incrementally using semantic import versioning would be a huge +1 in my book for adopting Go modules in this project.  (Please correct me if there is indeed a way to import both incrementally! :-) )

(As an addendum: I don't disagree with the reasons to hold off on Go modules listed above; I'm largely lamenting that Go modules weren't implemented in such a way that'd it make it easy for libraries like this one to adopt them while not breaking existing users.)

**Comment by aarondl** [comment]
You could fork v2 and change the imports to your own repo. It hasn't gotten any fixes/updates in quite a while so I'd say it's safe to do so. That way they're two separate packages again and should be usable side by side. Sorry to hear the migration is a pain. FWIW I think almost all of the changes were mechanical that you could write some go fix statements or use the go syntax/ast packages to rewrite the code easily if the code base is that large.

**Comment by ccpost** [comment]
It's a little less about sheer size of updates and more about blast radius and finding a time to do it when other conflicting changes aren't in-flight.

That's a great suggestion about forking and rewriting the import paths; I think this is route I'll go down. 👍

**Comment by aarondl** [comment]
Released.

**Comment by zikaeroh** [comment]
Wonderful! Note that the READMEs are still out of date for the new package path (sorry, I know you only released 20 minutes ago :smile:); you may want to update them so people don't get strange errors when they do `go get` without the version suffix.

Unfortunately there's no official "install this binary globally via modules" method yet (it's a WIP on the Go side), so you'll have to see which install/run examples you want to offer.

Unfortunately SQLBoiler is a little more complicated than most tools if you want to "fully pin" a version (i.e. not globally), as the drivers are separate binaries that need to exist in PATH with a very specific which make them difficult to use via the somewhat easy form like:

```
go run github.com/volatiletech/sqlboiler/v4 < driver binary name ? >
```

I used to have a few wrapper scripts to correctly pin `sqlboiler` and the `sqlboiler-psql`, but have recently moved to my own `go run`-able script that does what the `main` package does itself (so this version bump has no net negative for me).

**Comment by aarondl** [comment]
@zikaeroh For those that want version pinning I think the onus is on them to figure out how best to approach it. For now so long as we're in GOPATH mode it'll continue to work (I've amended the installation instructions to say as much). Thanks for pointing it out!
