### ISSUE TITLE
`omitempty` support for null.Type?

### ISSUE THREAD

**Issue by arhont375** [volatiletech/sqlboiler#385]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v3.0.1

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```go
type Some struct {
	CompanyName null.String `json:"companyName,omitempty" boil:"company_name"`
}
```

When marshaled to JSON `CompanyName` field is filled with `NULL` instead of omitting.

Is it an intended behavior? Is there any way to fix it?

**Comment by aarondl** [comment]
This is where it comes from, we put null intentionally. Passing back `nil, nil` actually makes the JSON marshaller just output nothing, which ends up failing to marshal properly.
https://github.com/volatiletech/null/blob/master/string.go#L55

I did some digging and I'm not sure if it's possible to return something that fits the world of `omitempty` if you're doing custom marshalling. It's behavior that's specially given to pointers, strings, and non-byte slices by the `json` package I think.

https://play.golang.org/p/8VWoWhm8iI1

If there's a way to fix this, I don't know it :)

**Comment by aarondl** [comment]
Closing unless there's something to do here.

**Comment by ImVexed** [comment]
Seems this could be fixed by using pointers:  https://stackoverflow.com/questions/33447334/golang-json-marshal-how-to-omit-empty-nested-struct

**Comment by aarondl** [comment]
@ImVexed thanks for the suggestion. Perhaps this could be a solution users can use in their marshalling structs.

**Comment by ImVexed** [comment]
@aarondl It would make for a temporary fix until https://github.com/golang/go/issues/11939 has an implemented resolution :/

**Comment by aarondl** [comment]
@ImVexed it's not something I'm prepared to do for sqlboiler. It is a large breaking change. Using pointers also is a bad way to give things null abilities because you lose control over allocation. Creating many pointers to small objects (like many null ints/bools/etc in your database structs) is a known good way to hurt performance of an application in Go because of the pressure it puts on the garbage collector.

Our hope is that the models work for serialization for some people but it's not an expectation that they do because people's serialization needs are too varied. The recommendation when the default behavior falls over is to create a serialization struct that does what you want.

**Comment by ImVexed** [comment]
As a follow up, I've found success going with a `modelsx` folder and [jsoniter](https://github.com/json-iterator/go) since it allows you to specify custom tags when marshaling I was able to specify multiple "views" of the same struct based on who is trying to marshal/unmarshal.

I also made a custom extension that plugs into jsoniter globally that makes `null.*` types play nice with `omitempty`:
```go
package helpers

import (
	"strings"
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/modern-go/reflect2"
)

func init() {
	jsoniter.RegisterExtension(&NullExtension{})
}

type NullExtension struct {
	jsoniter.DummyExtension
}

func (ne *NullExtension) CreateEncoder(t reflect2.Type) jsoniter.ValEncoder {
	if strings.HasPrefix(t.String(), "null.") {
		return &NullCodec{
			Type: t,
		}
	}

	return nil
}

type NullCodec struct {
	Type reflect2.Type
}

type NullType interface {
	IsZero() bool
	MarshalJSON() ([]byte, error)
}

func (nc *NullCodec) IsEmpty(ptr unsafe.Pointer) bool {
	return nc.Type.PackEFace(ptr).(NullType).IsZero()
}

func (nc *NullCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	if data, err := nc.Type.PackEFace(ptr).(NullType).MarshalJSON(); err == nil {
		stream.Write(data)
	}
}
```

But just to make sure anyone who stumbles across this is aware, it's using reflection so there is obviously risks of runtime panics if used improperly. So do be careful as any type that begins with `null.*` will get claimed by this extension and will probably fail the `IsZero` interface cast.

 If you're worried about that you can always make a custom config and call `RegisterExtension` on that instead of doing it globally.
