### ISSUE TITLE
Eagerloading, Nested struct, many-to-many

### ISSUE THREAD

**Issue by lunne** [volatiletech/sqlboiler#400]
First question:
Is the idea to be able to render an output (for an API) directly from the struct?
For example eager loading Groups into user would print this:
```
user {
  id 
  name
  groups [ 
    {id, name},
    {id, name}
  ],
  created_at
  updated_at
}
```
Is this possible? I have not found an example.

Also:
In the example of pilots on your page you do:
```
// "to many" relationship helper method.
// This will retrieve all languages for the pilot.
languages, err := pilot.Languages().All(ctx, db)
```
Is this working on MySQL? I have tried it on a many-to-many user-group test but i'm not getting user.Groups()

The relation works as this gives me the groups.
`models.Users(qm.Load("UserGroups.Group"), qm.Where("id=?", 1)).One(ctx, db)`

CREATE TABLE `user_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `group_id` int(11) NOT NULL,
  `created_by_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`,`group_id`),
  KEY `created_by_id` (`created_by_id`),
  KEY `user_group_groups_fkey` (`group_id`),
  CONSTRAINT `user_group_groups_fkey` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`),
  CONSTRAINT `user_group_users_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) 

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(40) NOT NULL,
  `given_name` varchar(150) DEFAULT NULL,
  `family_name` varchar(100) DEFAULT NULL,
  `created_by_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_ak` (`username`),
  KEY `created_by_id` (`created_by_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`)
) 

CREATE TABLE `groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `created_by_id` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `created_by_id` (`created_by_id`),
  CONSTRAINT `groups_ibfk_1` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
)

**Comment by aarondl** [comment]
@lunne: You've got two different questions going on in this issue.

1) You can render output directly from the struct, yes. They are currently all generated very JSON-friendly. You may wish to do some additional generation in order to customize how your JSON is generated (maybe you generate a `ModelJSON` struct for each struct that's slightly different.

You can also generate file types that are not `.go` files. There's documentation in the README about that. Good examples are Protobuf or Elm code.

One thing is that the `R` struct is -not- exported so JSON will not render anything. The reason for this is because you would have a structure that looks like this:

```json
{
  "id": "some id",
  "R": {
    "groups": [{"id": "some id", "name": "some name"}]
  }
}
```

The above seems unideal so if you want to include relationships you'll have to create your own structs. This is easy with embedding (you can embed the sqlboiler model and it'll serialize as expected).

2) Your many-to-many table does not look like a typical many-to-many table to `sqlboiler`. This is not documented properly here: https://github.com/volatiletech/sqlboiler#requirements but it should be.

I've added the phrase that talks about the problem your table has: In order for the many-to-many table to be transparent (no model generated for it) it must have a composite primary key that contains the 2 foreign keys to the tables it's joining **and no other columns** (in your table you have a `created_by_id`). If there is other columns, we cannot eliminate the model, and all your queries to retrieve the relationships must be done manually.

Hopefully this answers your questions.

**Comment by lunne** [comment]
Thanks,
Got it working when I removed all other columns.. 
But it would be good to be able to have atleast created_at, deleted_at in the m-2-m join table.

**Comment by lunne** [comment]
This is an example, is it the preferred way of dealing with relations when elimination of model is not possible? 
```
type UserJSON struct {
	*models.User
	Groups    models.GroupSlice   `json:"groups"`
	Companies models.CompanySlice `json:"companies"`
	CreatedBy *models.User        `json:"created_by"`
}
user, err := models.Users(
		qm.Load("GroupMemberships.Group"),
		qm.Load("Staffs.Company"),
		qm.Load("CreatedBy"),
		qm.Where("id=?", 1)).One(ctx, db)
	dieIf(err)
	myuser.User = user
	groups := myuser.User.R.GroupMemberships
	companies := myuser.User.R.Staffs
	dieIf(err)
	for _, g := range groups {
		myuser.Groups = append(myuser.Groups, g.R.Group)

	}
	for _, company := range companies {
		myuser.Companies = append(myuser.Companies, company.R.Company)
	}
	myuser.CreatedBy = user.R.CreatedBy
	fmt.Println(pprint(myuser))
```

It outputs something like this:
```
{
  "id": 1,
  "username": "SYSTEM",
  "groups": [
    {
      "id": 1,
      "name": "admin",
    },
    {
      "id": 2,
      "name": "user",
    }
  ],
  "companies": [
    {
      "id": 1,
      "name": "Some Company",
    }
  ],
  "created_by": {
    "id": 1,
    "username": "SYSTEM",
  }
}

```

**Comment by aarondl** [comment]
Pretty much. Though I'm not sure why you're doing appending at all. Can't you just assign the relationship slices into the `myuser.Groups` and `myuser.Companies`?

**Comment by lunne** [comment]
Yes, you are correct, I think I went from printing to appending and then copy+paste without thinking so much about it.

**Comment by lunne** [comment]
I have looked at this again and thats not possible `myuser.Groups` and `myuser.Companies` are `models.GroupSlice` and `models.CompanySlice` 
So thats why I need to iterate it rebuild the slice. 

Is there a way to get the slice and assign it the way you propose?

**Comment by aarondl** [comment]
Those slice types are simply type aliases for: ```[]*models.Group```, so you should be able to convert it just by doing: ```([]*models.Group)(myuser.Companies)```.

**Comment by lunne** [comment]
I'm sorry, but can you post an example of this?
