### ISSUE TITLE
RowsAffected in the API

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#41]
We're considering doing this but it's a breaking change.

So far we can't come up with any real use case of when you would want to use this, but we see it in other public APIs. If you require this feature please Thumbs up this issue instead of making a new one.

So people get a better idea of what I mean I'll edit here:

Currently queries like Update/Delete etc do not return rows affected:

```
jet, err := models.Jets(tx).One()
jet.Fast = true
err := jet.Update(tx)

jets, err := models.Jets(tx).All()
err := jets.UpdateAll(tx, models.M{"fast": true})
```

After this change they would:

```
jet, err := models.Jets(tx).One()
jet.Fast = true
affected, err := jet.Update(tx)

jets, err := models.Jets(tx).All()
affected, err := jets.UpdateAll(tx, models.M{"fast": true})
```

This is a breaking change and will be driven by user need. Please let us know.

**Comment by nullbio** [comment]
If you could also describe your use case that would be helpful too. Thank you.

**Comment by SlinSo** [comment]
It is interesting to see if an update really changed the data (affectedRows > 0).
i have 2 use cases:

1. That way you could insert data to an audit table only if it changed and you dont't have to compare the data yourself. Maybe you dont't want to load the whole data prior to the update statement.
2. Statistics for background jobs.

**Comment by ilikebits** [comment]
I use the number of affected rows to determine whether a query was "successful". For example, the system I'm working on allows users to specify parts of a query, and treats a query affecting 0 rows as an error (e.g. maybe the user made a typo). For performance and correctness reasons, it's preferable to do this in 1 query rather than doing a `SELECT COUNT` after the deletion.
