### ISSUE TITLE
"columns" in table name causes function collision.

### ISSUE THREAD

**Issue by lunemec** [volatiletech/sqlboiler#413]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.1.0

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
CREATE TABLE project ()

CREATE TABLE project_columns ()

### Further information. What did you do, what did you expect?
Upon generation the name of table "project_columns" and "project" cause the code generated to have 2 public functions named `ProjectColumns`:
project.go:
```
func (o *Project) ProjectColumns(mods ...qm.QueryMod) projectColumnQuery {}
```

project_columns.go:
```
func ProjectColumns(mods ...qm.QueryMod) projectColumnQuery {}
```

I understand this was caused by the table naming, but it probably should throw error upon generation that this is incorrect, or be handled by mangling the names somehow (I prefer the error).

**Comment by aarondl** [comment]
One of v3's big ticket items was Aliasing table names so that these sorts of collisions can be solved by the user (you :D). I was thinking about generating error messages when a collision was detected but ultimately your code doesn't compile which is good enough for me and imitating the Go compiler's ability to detect these problems is way too much work for way too little payoff :)

https://github.com/volatiletech/sqlboiler#aliases

If I'm somehow misread your issue or aliases is not the solution re-open and let me know :)
