### ISSUE TITLE
complex where clauses

### ISSUE THREAD

**Issue by aaabbbccc-123** [volatiletech/sqlboiler#448]
how to create a complex where clauses with the query builder? primarily, this is due to not want to hand craft the "in (?, ? , ...)" part.

a example is select * from table_a where (id= ? and type in (?,?,?) or type in (?,?) ) and price< ?;

but the actual generated one is select * from table_a where (id= ? and price <? and type in (?,?,?) or type in (?,?) )

The problem i am having is : WHERE and IN is not generated according to the order specified. instead where is generated first and then in clauses are generated.

**Comment by aarondl** [comment]
Hi there @aaabbbccc-123.

Thanks for reporting this issue. Thought I had replied to this but I guess I hadn't.

The problem here is rooted in that we keep in statements separate from where statements for whatever reason.

https://github.com/volatiletech/sqlboiler/blob/dev/queries/query.go#L37-L38

So all the normal `where` ones get processed before `where in` which doesn't make any sense at all. Will try to fix this soon-ish, but am currently wanting to get this new feature finished first.

**Comment by aarondl** [comment]
Dev branch should have this issue fixed. Where and WhereIn are no longer separate internal data structures so they should be ordered in whatever way you put them in your query.
