### ISSUE TITLE
boil.Columns feature: Whitelist and Select query mod

### ISSUE THREAD

**Issue by tiger5226** [volatiletech/sqlboiler#449]
I used a select mod in a query, because there are a lot of columns and I did not think it needed to load all the data. I am changing one of the columns in the select query mod. 

1 - `item.UpdateG( boil.Infer())` Does not update anything.
2 - `item.UpdateG(boil.WhiteList("mycolumn"))` does not update anything.
3 - `item.UpdateG(boil.GreyList("mycolumn"))` produces error about unknown column `""` empty string. 
4 - I remove the `qm.Select(...)` query mod  and use the `boil.Infer()` it updates perfectly fine. 

Is there something special in V3 around using the new Columns feature and Select mods?

**Comment by tiger5226** [comment]
I am sorry, I am a bit confused. I don't know the internals that well. Are you saying that doing the select query mod, and then trying to update that instance using the new columns feature will not work or something else?

**Comment by aarondl** [comment]
No. But then it wasn't really clear what you were doing to me until what you just posted.

That should work fine. I'd be very curious to see more details about what's going on. The whitelist one is the most surprising because that's an extremely straightforward query.

Maybe provide a lot more detail, things like what type the column is in the database (nullable? Unique? Int? String?). Did you select the ID of the database object so it knows what to update? Are you using mysql? 

Also it'd be useful to see the queries you've made.

Is it just: select("a"), update(boil.Whitelist("a"))?

Keep in mind Infer will be downright dangerous if you have not selected the entire record. DO NOT use infer or it will end up overwriting data with the zero values in the struct. There is no metadata in the struct that tells sqlboiler what fields are "dirty" or "active" and as such infer will just update all your columns (except columns with default values).

**Comment by aarondl** [comment]
This seems to be stale.

**Comment by yourtallness** [comment]
Can confirm that passing a greylist to the update columns in an `Upsert` operation results in:

```
sqbmodel: unable to upsert posts: ERROR: syntax error at or near "=" (SQLSTATE 42601)
```
