### ISSUE TITLE
UpdatedAt not updated when updating

### ISSUE THREAD

**Issue by edwardmp** [volatiletech/sqlboiler#453]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.1.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
```
colsToUpdate := []string{"title"}
_, err := damageCategory.Update(ctx, db, boil.Whitelist(colsToUpdate...))
if err != nil {
    return nil, err
}
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```
CREATE TABLE damage_categories(
    uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_type INT NOT NULL,
    title varchar(255),
    estimated_price NUMERIC(10,2) NOT NULL,
    created_at timestamp DEFAULT NOW() NOT NULL,
    updated_at timestamp DEFAULT NOW() NOT NULL,
    UNIQUE (title, asset_type)
)

```
### Further information. What did you do, what did you expect?

I expect that `UpdatedAt` is set to the current time. The record is updated in the database, but the timestamp is not updated.

Thanks for creating SQLBoiler though, I really like it!

**Comment by aarondl** [comment]
Currently `Whitelist` means a whitelist, nothing else gets through that kind of specification meaning your timestamp columns are also excluded from being updated.
If you want to only update those three columns you have to spell all three of them out in the Whitelist.
Greylist may be useful to you in these scenarios.

I'll consider this resolved as it's working as intended but feel free to continue discussion if you think it shouldn't be like this etc.

Glad you like SQLBoiler :D

**Comment by edwardmp** [comment]
@aarondl 

Thanks for the quick reply. I guess that makes sense, but maybe it's a good idea to include this in the README? I had almost assumed that these columns would be whitelisted by default.

**Comment by aarondl** [comment]
Added a bit to the README: https://github.com/volatiletech/sqlboiler/tree/dev#update

The problem with the global greylist or any such automatic piece is that you can NEVER turn it off if you need to. Which is why `Whitelist` is the way it is.

Whitelist and Blacklist are there as absolutes so you have full control. The Greylist allows you to simply say: "also update this column" in addition to whatever else it would have updated (the timestamps in this case). Though the bad part about Greylist is it'll also add all the other columns back.

I'd say that maybe we are missing a Whitelist+Timestamps type of list. I could see us either:
* Making a new type of `Columns` specification (Whitelist+Timestamps).
* Making `Whitelist` always update columns and changing the behavior of the recently added `boil.SkipTimestamps` so that it also modifies the columns so you still have control over it.

It's more likely that we do the first one even though it's probably the least desirable of the two to avoid suddenly changing the behavior of Whitelist for those people currently using it.

Keep in mind it's very easy for you to do this yourself too:

```go
func WhitelistTimestamps(columns ...string) boil.Columns {
  return boil.Whitelist(append(columns, "created_at", "updated_at"))
}
```

**Comment by edwardmp** [comment]
Thanks for adding to the readme, awesome!
The use case of greylist is not really clear to me. If whitelist equals `all - primary`, and greylist is `all - primary + greylist`, what can possible included in the greylist except the primary?

From a design standpoint, not providing a global greylist does indeed make sense.

The final approach you suggest does some convenient enough to use in my case, so thanks for that.
