### ISSUE TITLE
Wishlist: subselect support

### ISSUE THREAD

**Issue by autarch** [volatiletech/sqlboiler#482]
It'd be great if sqlboiler could provide some support for subselects. Right now the only way I can find to do this is something like this:

```go
subselect := "SELECT foo_id FROM foo WHERE name = ?"
models.Bars( fmt.Sprintf( "%s = ( %s ) ", models.BarColumns.FooID, subselect ), name )
```

This is pretty gross and I can't use sqlboiler at all for the subselect query.

The most minimal solution would be to add a method to the `barQuery` struct generated for each table to have a new method that returns what the underlying `query.BuildQuery` method would return.

Then at the very least I could do this:

```go
subselect, binds := models.Foo( qm.Select( models.FooColumns.FooID ), models.FooWhere.Name.EQ(name) )
models.Bars( fmt.Sprintf( "%s = ( %s ) ", models.BarColumns.FooID, subselect ), binds... )
```

That'd be an improvement, but even better would be to make it possible to pass a subselect to the generated `EQ` (and other) methods. This is obviously a lot more work but it'd be a lot nicer.

**Comment by aarondl** [comment]
Hmm. You're right in that it's desirable to do that. Though I think the entire idea of passing subselects to EQ methods etc. is a bad idea. One of the key reasons those exist is so that you cannot pass in a type that's incorrect into that. If we went down this road that type parameter would become `interface{}` and we'd lose the compiled type safety those were designed to create.

You might have trouble even if you had `query.BuildQuery` at your disposal because the indexes of the arguments passed in might get messy. Since when you call `BuildQuery` it evaluates the `?` and changes them into `$1` for postgres. Then when you did the outer query it's perhaps possible to get a second `$1` generated...
It's a tricky feature given that no provisions were made for it earlier.

Maybe the where query mod could become aware of this. Since it's already poisoned by having any number of arguments.

```go
models.Bars(qm.Where("happiness = ?",
  qm.Subselect(
    models.Foo(qm.Select(models.FooColumns.FooID), models.FooWhere.Name.EQ(name)),
  ),
)
```

**Comment by aarondl** [comment]
This appears stale.

**Comment by RichardLindhout** [comment]
@aarondl We're having issues with this. It works in mysql but not in postgres.

https://github.com/web-ridge/gqlgen-sqlboiler/issues/25

**Comment by aarondl** [comment]
@RichardLindhout I've returned. However I'm not really interested in adding this feature myself, though I would not reject a PR that had it. In my current projects I simply drop to raw sql when things get this complicated and use my checker to ensure that I'm not messing up.

I'm not sure how you'd go about implementing it, as I said above it's quite a tricky one.

**Comment by RichardLindhout** [comment]
My proposal:

BuildQuery calls BuildQueryAdvanced with UseIndexPlaceholders true

We can use the BuildQueryAdvanced to disable the UseIndexPlaceholders for the subquery.

**Comment by RichardLindhout** [comment]
Or BuildQuery() and BuildSubQuery() both calling buildQueryAdvanced with true/false

**Comment by RichardLindhout** [comment]
Also the subQuery should not have the last `;`. Would you accept a PR with that approach?

**Comment by RichardLindhout** [comment]
Something like this:
```
package queries

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/volatiletech/strmangle"
)

var (
	rgxIdentifier = regexp.MustCompile(`^(?i)"?[a-z_][_a-z0-9]*"?(?:\."?[_a-z][_a-z0-9]*"?)*$`)
	rgxInClause   = regexp.MustCompile(`^(?i)(.*[\s|\)|\?])IN([\s|\(|\?].*)$`)
)

type QueryOptions struct {
	SemiSuffix bool
	UseIndexPlaceholders bool
}

var queryOptions = QueryOptions{
	SemiSuffix: true,
	UseIndexPlaceholders: true,
}

// BuildQuery builds a query object into the query string
// and it's accompanying arguments. Using this method
// allows query building without immediate execution.
func BuildQuery(q *Query) (string, []interface{}) {
	return BuildQueryWithOptions(q, queryOptions)
}

var subQueryOptions = QueryOptions{
	SemiSuffix: false,
	UseIndexPlaceholders: false,
}

// BuildSubQuery builds a query object into the query string
// and it's accompanying arguments. Using this method
// allows query building without immediate execution.
func BuildSubQuery(q *Query) (string, []interface{}) {
	return BuildQueryWithOptions(q, subQueryOptions)
}

// BuildQueryWithOptions builds a query object into the query string
// and it's accompanying arguments. Using this method
// allows query building without immediate execution.
func BuildQueryWithOptions(q *Query, o QueryOptions) (string, []interface{}) {
```

Full code in https://github.com/web-ridge/gqlgen-sqlboiler/issues/25

**Comment by aarondl** [comment]
Sorry @RichardLindhout for the delay on this.

It looks to me like the code that you've created would only allow subselects in mysql but that it would break in postgres is that correct? I think the only way we could have proper subquery support is to be able to pass a query object as a query argument and have it evaluated properly via recursion. Something like this as a supported API:

```
models.Users(qm.Where(`id = ?`, models.Videos(some group by having > 2 videos))).All()
```

**Comment by RichardLindhout** [comment]
In mysql it did work without any changes. When not placing indexed placeholders in the subquery it works in postgres too according to @troian. We found that surprising but that would mean we would have a lot less work to do to support subqueries but maybe it's too good to be true.

Ideally we would do the thing you mention as an api and calling the BuildSubQuery func somewhere here https://github.com/volatiletech/sqlboiler/blob/fad098aa2ba38220c0727620b7ea665983aec26e/queries/query_builders.go#L366?

**Comment by aarondl** [comment]
@RichardLindhout Well, it could perhaps work depending on how late the ? are converted into $1. What we need is some proof! Perhaps by test or something for both mysql and postgres in different parts of the query (in `where`, but also in `from` etc).

Though I am still concerned about the API compared to what I was presenting to you. It's simply not a very discoverable API. In the one I posted above - you simply do what you'd expect to work and it does. In the proposed one people would have to try the normal thing find out the problems with it, track down docs (or an issue that points them to docs) to find that the proper way to do it is to use some odd `BuildSubQuery` method that's not otherwise present.

In regards to your question it would have to be more general than that. whereKindIn/NotIn also make sense to use subqueries.

**Comment by RichardLindhout** [comment]
I agree with you, would you like a PR if the buildSubquery function had proper tests too?

We should also add this with the api you mentioned but I don't know exactly how to handle that yet.

**Comment by aarondl** [comment]
Hi @RichardLindhout. I don't think it's the route I want to take. I'd rather people continue to do the raw queries over end up with this API as the way we do subqueries and have to keep this around until v5. Sorry about that :(

**Comment by josemarluedke** [comment]
I was also looking for sub select support, it's unfortunate that it's not implemented. Using postgres here.

**Comment by RichardLindhout** [comment]
@josemarluedke you could use one of the two workarounds @troian provided to disable the UseIndexedPlaceholders in the buildquery here https://github.com/web-ridge/gqlgen-sqlboiler/issues/25
