### ISSUE TITLE
Is there any way to inspect the content of a Query struct?

### ISSUE THREAD

**Issue by oortlieb** [volatiletech/sqlboiler#497]
I'm currently working on implementing soft-delete functionality in our generated code by modifying the default `sqlboiler` templates. The general strategy so far is to append an additional condition (`deleted is not true`) to queries when the table has a `deleted` column on it. So far, I've updated the finalizers (`One`, `All`, `Count`, and `Exists`).

This seems to works great for making sure that we omit soft-deleted rows. My question, however, relates to how to offer an API for selected soft-deleted rows. Ideally, if an incoming query has a value specified for `deleted`, the finalizer would use that value, instead of overwriting it.

Is there a way we could implement this? Based on the docs I've read, the (model)Query structs don't appear to offer any information about the values set in them. The alternative would be to provide an additional function for considering soft-deleted rows, but my preference would be to avoid additional functions just for getting soft-deleted rows.

What I think I'm looking for is something like this:

```
if !q.Query.HasWhere("deleted") {
  queries.AppendWhere(q.Query, "deleted_at is null")
}
```

**Comment by aarondl** [comment]
There's no way to introspect a query. It wasn't an anticipated use case so there's no way to do it that I can think of because nothing is exported. So you could fork the `queries` package I suppose. And although it's preference to not have additional functions it is (for better or worse) the design of sqlboiler to create additional functions instead of altering the templates or core functionality. Quite often in a project I'll create a `modelsx` package, this has validation hooks, transaction helpers, and also any additional queries/query starters I need. It'd be very simple to create a `modelsx.Users` that doesn't (or does) return deleted rows.

You could argue that that's dangerous because the difference between modelsx/models is a small enough difference to be able to easily make a mistake and I would agree. I don't have any solid advice around that other than additional tooling to prevent misuse. Though if you were to add a bool to your created helpers that determined whether or not deleted users were returned or not that could also maybe help since then modelsx/models have a different type signature. (Could also be a new trinary type: NoDeleted | Deleted | Both to add flexibility)

FWIW I found even in rails overriding the default behavior (even with all their powerful dark magic) proved detrimental and we eventually added explicit helpers to add the where clauses to our queries because it broke other queries that didn't care about deleted status and it was difficult to change that behavior based on the presence of a where clause (just like it is in sqlboiler).

I will close this because it's not an active issue and is more of a question as the way sqlboiler's been designed there is a recommended solution that works fine, but feel free to respond, I'd be glad to continue the conversation.
