### ISSUE TITLE
Raw Query Bind Silently Fails

### ISSUE THREAD

**Issue by sachnk** [volatiletech/sqlboiler#498]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.1.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```go
{
	type myobj struct {
		Value string `boil:"val"`
	}

	obj := myobj{}
	if err := queries.Raw("SELECT 'foo' AS val").Bind(ctx, db, &obj); err != nil {
		panic(err)
	}

	fmt.Println(obj)
}

{
	type myobj struct {
		Result int64 `boil:"res"`
	}

	obj := myobj{}
	if err := queries.Raw("SELECT 1 AS res").Bind(ctx, db, &obj); err != nil {
		panic(err)
	}

	fmt.Println(obj)
}
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

```
{foo}
{0}
```

### Further information. What did you do, what did you expect?

Expected output:

```
{foo}
{1}
```
It seems that the `Bind()` command on raw queries requires uniqueness with the name of the struct that is provided. If the user of `Bind()` inadvertently uses a struct that has the same struct name that was used in a previous invocation of `Bind()`, it ***silently*** fails.

This seems quite dangerous.

A cursory review of the `Bind()` code suggests that the `<package-name>.<struct-name>` is used as some sort of key. But that key can easily collide. 

Is this expected behavior or did we miss something?

**Comment by aarondl** [comment]
@sachnk That's exactly how it works. In order to get very fast binding we implemented a caching mechanism for the types that are bound to as well as caching a lookup for a specific set of columns. It wasn't previously considered that users would be defining types outside of global scope (at which point it's impossible for this name to collide) and so the "easily" part was overlooked. It's also unfortunate that Go seems to name these types the same (both are `main.myobj`).

As for the silent failure it's a "feature" that was implemented long ago. The problem was if you do `select * from users;` and then at some point unbeknownst to your sqlboiler models you add a column (a non-breaking change to the database schema) then suddenly `Bind()` would begin failing saying that it couldn't find something to bind that returned column to. This shouldn't be an issue if the caching mechanism wasn't having a collision.

I'm currently considering how to create a proper key given this information. It's looking sad :(

**Comment by aarondl** [comment]
Spent a bunch of time evaluating different methods of "hashing" the type. Currently in order to not have extra dependencies we don't actually perform any hash on the types, we just append some strings. Today I thought I'd try a fast non-cryptographic hash (xxhash) to see if it could be improved. It actually speeds up the hash generation, reduces allocations for hash key creation as well as reduces the size of the hash to 8 bytes for any input. It's all very desirable but I couldn't accept the additional cost of another dependency currently.

```
BenchmarkMakeCacheKey-8        	 3000000	       429 ns/op	     192 B/op	       1 allocs/op
BenchmarkMakeCacheKeyXX-8      	 3000000	       479 ns/op	       0 B/op	       0 allocs/op
BenchmarkMakeCacheKeyBoth-8    	 5000000	       352 ns/op	       0 B/op	       0 allocs/op
BenchmarkMakeCacheKey2-8       	 5000000	       398 ns/op	     176 B/op	       1 allocs/op
BenchmarkMakeCacheKey2XX-8     	 3000000	       482 ns/op	       0 B/op	       0 allocs/op
BenchmarkMakeCacheKey2Both-8   	 5000000	       339 ns/op	       0 B/op	       0 allocs/op
BenchmarkMakeTypeKey-8         	  500000	      2744 ns/op	     776 B/op	      42 allocs/op
BenchmarkMakeTypeKeyXX-8       	  500000	      3073 ns/op	     328 B/op	      41 allocs/op
BenchmarkMakeTypeKeyBoth-8     	  500000	      2665 ns/op	     328 B/op	      41 allocs/op
```

These are the cache key creating methods that we have now. You can see that the XX version improves in allocations but loses in speed but if we combine the use of a `strmangle.GetBuffer` which appends all the strings, and only do the hash at the end (`Both` benchmarks) we win on both allocations and speed.

Anyway, the solution to this problem I came up with was to include not only the name of the type, but the ordered names and types of the fields within it. This is a large increase in the size of the hash key and hurts the computation speed of the hash key quite a bit hence wanting to improve it with xxhash, perhaps we'll revisit that in the future. Fixed on the dev branch, your output now looks like:

```
SELECT 'foo' AS val
[]
{foo}
SELECT 1 AS res
[]
{1}
```
