### ISSUE TITLE
Does eager loading do joins, or separate queries?

### ISSUE THREAD

**Issue by e-nikolov** [volatiletech/sqlboiler#510]
When I enable the debug logging I see a separate query being printed for each of the eagerly loaded relationships, but i was under the impression that qm.Load() would automatically do joins where possible.

**Comment by aarondl** [comment]
It currently does separate queries. There's room for improvements if it were able to use joins in some way, but I think it'd require a complete rewrite of the entire eager loading system. Sorry for this! I wish it would use joins where possible too.

**Comment by requaos** [comment]
This truly is unfortunate, for places where I have observed this impact
performance I use qm.SQL() to write the query myself as a workaround. I
hope this helps.

**Comment by razor-1** [comment]
I was looking for this also. It's really too bad, because everything works great with `Load`. But issuing separate queries for every related table is a nonstarter from a performance perspective, at least for us.  I tried playing around with InnerJoin and building up the query that way, but then the relationship doesn't seem to get set up correctly so that it can be easily accessed via `.R`.

**Comment by aarondl** [comment]
@razor-1 Relationships are never set by InnerJoin as it's not meant to be relationship aware. That's simply there for you to be able to pull in extra data in the case you need to do where statements on it or perhaps do custom binding to get specific columns back.

This issue is somewhat unfortunate though.

**Comment by tonyhb** [comment]
Could we potentially start a backlog of issues for refactors like this using labels?  I'm wondering if that may inspire people to help out.

I do agree that questions should be closed out!
