### ISSUE TITLE
Exists() finisher complaining about QueryMod and context

### ISSUE THREAD

**Issue by ddibiase** [volatiletech/sqlboiler#520]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.2.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```
exists, err := models.Users(
	ctx, db, qm.Where("Email=?", req.Email),
).Exists()
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

Pretty basic User table, nothing special.

### Further information. What did you do, what did you expect?

Using a similar syntax to the README file:
```
exists, err := models.Pilots(ctx, db, Where("id=?", 5)).Exists()
```
The error I'm receiving is:
```
services/users.go:53:29: cannot use ctx (type context.Context) as type qm.QueryMod in argument to models.Users:
	context.Context does not implement qm.QueryMod (missing Apply method)
services/users.go:54:9: cannot use s.Db (type *sql.DB) as type qm.QueryMod in argument to models.Users:
	*sql.DB does not implement qm.QueryMod (missing Apply method)
services/users.go:55:10: not enough arguments in call to models.Users(ctx, s.Db, qm.Where("Email=?", req.Email)).Exists
	have ()
	want (context.Context, boil.ContextExecutor)
```
Not sure what's happening, but it seems like I'm following the instruction/example correctly.

On another note, why do we need to keep passing ctx in? Is there a way to pass ctx and db in as a global for all requests so it doesn't need to be repeated all the time?

**Comment by aarondl** [comment]
Ugh. This is a case of documentation rot. Sorry, I'll update the docs to reflect what it really is now:

```
exists, err := models.Users(
	qm.Where("Email=?", req.Email),
).Exists(ctx, db)
```

This changed in sqlboiler v3, missed this bit of documentation when updating the readme.

As for your question:
ctx specifically cannot be passed in globally, that's exactly the opposite of what it's meant for. Read up on the context package (https://golang.org/pkg/context/) to understand why this is the case and why context could be useful to you if you continue to pass it in everywhere. Note that you have a context object in any standard http handler (http.Request.Context is a method you can call to get the http request context to feed it in here). sqlboiler does have a command line flag/configuration file piece to disable context, see documentation / `--help` output.

Passing in DB globally is possible as well through a flag, because it's not a recommended way to do things since v3 we hide this feature behind a flag. See the option `add-global-variants`.

**Comment by ddibiase** [comment]
Thanks for clarifying that. Yeah I ended up digging deeper into Context and determining how to pass it in via my apps needs. We're building gRPC endpoints and each come with a context, so I'm binding that in.

Regarding the global db I agree, we ended up finding a good pattern for filtering it through the gRPC endpoints. Again thanks for your response. :-)
