### ISSUE TITLE
custome types

### ISSUE THREAD

**Issue by Dexus** [volatiletech/sqlboiler#521]
Hello,

I'm looking for custome types, that use application side encryption.

My Custome Type use Values and Scan so that the JSON Struct encrypted and stored.

But now I would like to use it with SQLBoiler how can I use it now?

**Comment by aarondl** [comment]
You can use it one of two ways:
- Use type replaces in the configuration file (this may not work if the type is conditional on things the type replacer has no access to)
- Fork the driver code and create your own driver that returns the correct types (this is fullproof because you have access to all the data to make the decision if it should be an encrypted field or not)
