### ISSUE TITLE
Question about insert, update, upseart cache

### ISSUE THREAD

**Issue by KoteiIto** [volatiletech/sqlboiler#535]
The queries are cached in the map by the insert, update, and upsert functions, but it seems that these caches are not deleted. Do you encounter problems such as lack of memory?

https://github.com/volatiletech/sqlboiler/blob/master/templates/15_insert.go.tpl#L194

 would like to modify the template if there is a possibility that a problem might occur, but the upsert template could not be modified because it is managed by the driver.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.3.0

**Comment by aarondl** [comment]
The things in the cache are fairly small (just strings) and I don't think they'd represent a huge percent of memory usage in any application. Keep in mind that it scales with the number of queries you're doing since it's a cache. I don't think any one application is doing -that- many queries that this cache would ever become a problem.

I'd accept a PR that creates a `--smart-cache` option that would create a cache that does eviction (which eviction mechanism needs to be well thought out of course).

As for not being able to modify the template for the driver, all you need to do is modify the template's driver and recompile it :)

Closing this as I think I've answered everything.
