### ISSUE TITLE
Escaping parameters in an order-by clause

### ISSUE THREAD

**Issue by emwalker** [volatiletech/sqlboiler#546]
This is a request for information and a possible feature request.  I would like to be able to add an order-by clause with a parameter using the query builder DSL.  E.g.,

```golang
mods = append(
  mods,
  qm.OrderBy("(topics.name ilike ?) desc, topics.name", searchString),
)
```

Looking at the code on `master`, this doesn't seem to be supported yet.  Another possibility would be to be able to escape the string before it's passed to `OrderBy`:
```golang
mods = append(
  mods,
  qm.OrderBy(fmt.Sprintf("(topics.name ilike %s) desc, topics.name", qm.Escape(searchString)),
)
```

For this particular case, I would prefer to use the query builder rather than construct a raw query, as it makes it much easier to pick and choose what is to be added to the query.

Is there a recommended way of handling this situation?

**Comment by aarondl** [comment]
Hmm. Without proper support built into the `queries` package this is not possible (sorry for that). It's very unlikely that `qm.Escape` will ever come to fruition because of how damned complicated escaping is for each of these databases (hence us relying on the Go mechanic of prepared statement sending to the DB server for actual escaping).

I would accept a PR to modify OrderBy to additionally accept a variadic argument list of args just like where does so they can properly be appended.

**Comment by emwalker** [comment]
@aarondl I've made a pull request for this [here](https://github.com/volatiletech/sqlboiler/pull/593).  I assume changes will be needed.

**Comment by ImVexed** [comment]
Was the previous merge request reverted? As of v4.5.0 `OrderBy` doesn't seem to accept parameters now :( https://github.com/volatiletech/sqlboiler/blob/v4.5.0/queries/qm/query_mods.go#L469

**Comment by aarondl** [comment]
It seems like @emwalker may have forgotten to update the query mod, despite doing all the work to enable the arguments and I didn't pay close enough attention. Seems like `Having` and `GroupBy` could both be updated to take a variadic list of arguments now that we have the piping to allow them to function.

**Comment by emwalker** [comment]
My apologies.  I ended up not using this functionality, so I didn't notice that the query mod needed to be updated as well.
