### ISSUE TITLE
ForeignFN conflicts with ColumnName

### ISSUE THREAD

**Issue by bugzpodder** [volatiletech/sqlboiler#576]
I am seeing a conflict in all my foreign keys for these two function.
I can see that if you have user_id as a foreign key, you would get UserId as field and User() as foreign function?

ForeignFn: https://github.com/volatiletech/sqlboiler/blob/7d3d954a4be10dc06b9464fb3e6d74836274c467/boilingcore/text_helpers.go#L40

ColumnName:
https://github.com/volatiletech/sqlboiler/blob/4dea9a5f77e3ec6090ad455df3d408e47e077700/boilingcore/aliases.go#L78

I found the following logic help:
```
       if foreignFn == fkColumnName {
		if strings.HasPrefix(foreignFn, foreignTableName) {
			foreignFn = foreignTableName
		} else {
			foreignFn += foreignTableName
		}
	}
```
So if you have CreatedBy to the User table, it would generate foreignn fn CreatedByUser()
and if you have UserIdentifier on the User table, foreign fn would be User()

I know there are aliases in the config file, but when every table have a User field called created_by, it seems to be troublesome to have set same alias across 100 tables.  If aliases work from the destination table or there is a global list of aliases that would be great as well.

**Comment by aarondl** [comment]
This sort of logic is already present. If there is no short-form available and it would cause a conflict then it uses the foreign key name + the other table name. Take this example in the documentation of `txtNameToMany`:

```
// industries - industries
// industry_id  mapped_industry_id
// fk == table = industry.Industries
// fk != table = industry.MappedIndustryIndustry
```

Not pretty but it should avoid any problems. Is it perhaps that you're using the uppercase fork that you've made (the PR) and you're running into equality troubles or something?

**Comment by bugzpodder** [comment]
Let's just talk about the lower case scenario.  I was rambling a bit, but I think the issue is this:
1) Completely different names.  Consider you have books table and it has author column, pointing to users.ID

then author column would both be field (Author) and foreign function Author().
Similarly if you have a "created_by" column pointing to users.ID
or perhaps a non standard suffix, so instead of user_id, you had user_name, then field (UserName) and function UserName() would conflict.

This happens when trimSuffixes does nothing, ie when your columns doesn't end with _id.

After my change, you would have:
Author, AuthorUser()
CreatedBy, CreatedByUser()
UserName, User()

I know in sqlboiler config you have the option to rename these fields (haven't tried it).  However it is not ideal because its possible that every table has their users foreign key to be CreatedBy, so you'd have to alias it for every single table.

Instead, we could have global aliases, which renames CreatedBy() to User() for every foreign key function, or foreign aliases on the table users.

**Comment by aarondl** [comment]
So to make a clear example with created_by and user.id:

We have:
```
books: created_by (foreign key references user.id)
users: id
```

So this is a many to many, in which case the txtNameToMany rules apply.

I added a test to check this scenario and the output (ignore the want, it's dummy values to make the test fail so we can see results) is:

```
--- FAIL: TestTxtNameToOne (0.00s)
    text_helpers_test.go:50: 10 local wrong: CreatedByBooks want: User
    text_helpers_test.go:53: 10 foreign wrong: CreatedBy want: What
```

So on the local table (books) the one with the `created_by` column, there is no conflict because the name becomes `CreatedByBooks`, and on the foreign table the function name is `CreatedBy`. So to be clear, you're not happy because `CreatedBy` is conflicting with the user table's `created_by` column, not the book's created_by column? Just trying to wrap my head around still sorry.

**Comment by bugzpodder** [comment]
Maybe its clearer as an example:
```
CREATE TABLE author (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    email VARCHAR(25) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE book
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (created_by) REFERENCES author (id)
);
```

```
// Book is an object representing the database table.
type Book struct {
        ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
        Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
        CreatedBy int       `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
        CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

        R *bookR `boil:"-" json:"-" toml:"-" yaml:"-"`
        L bookL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```
```
// CreatedBy pointed to by the foreign key.
func (o *Book) CreatedBy(mods ...qm.QueryMod) authorQuery {
        queryMods := []qm.QueryMod{
                qm.Where("id=?", o.CreatedBy),
        }

        queryMods = append(queryMods, mods...)

        query := Authors(queryMods...)
        queries.SetFrom(query.Query, "\"author\"")

        return query
}
```

So here on Book struct, we have both CreatedBy column, and CreatedBy method.  And Golang complains about this.  Maybe this helps clear things up a bit?

**Comment by aarondl** [comment]
Well, let's think about a final proposal for how we should name things in the case that `trimSuffixes` does nothing and there would be a conflict. This only looks at one-to-many and one-to-one given that that's all we're proposing to modify at this time (it's possible pluralization is saving us in the many-to-many cases). Potentially conflicting cases (where trimsuffixes does nothing and the column name == the foreign name) are highlighted in bold.

If we have `users` and `videos`:

| fk column |  local [user] (now)  |  foreign [video] (now) | local [user] (patch) | foreign [video] (patch) |
| ------------- | ----------------- | ------------------ | ----------------- | ------------------- |
| videos.user_id (baseline) | Videos | User | Videos | User |
| videos.created_by | CreatedByVideos |  **CreatedBy** | CreatedByVideos | CreatedByUser |
| videos.user | Videos | **User** | Videos | *UserUser* |

I've italicised the problem with the provided code, `UserUser` is not a good name, but there's also nothing else that fits. `UserTable` is bad because it starts to invade the domain language with random sql pieces to avoid a naming conflict (because the correct name -IS- `User`). `VideoUser` is bad because it stutters: `video.VideoUser`. I'm learning towards `VideoUser` because it's all we can do.

This is the proposed change then (your original change + `videos.VideoUser`)?

**Comment by bugzpodder** [comment]
Yes, VideoUser seem to be the best name.

**Comment by hugbubby** [comment]
This is still an issue btw

**Comment by yuzuy** [comment]
@aarondl I encountered this issue. Let's discuss it again and fix this issue.
If I use "created_by" for a column name, I can't use sqlboiler.

**Comment by aarondl** [comment]
@yuzuy happy to accept a PR that behaves as I spec'd out above.

**Comment by konrin** [comment]
What are the solution options?
Maybe through aliases?

**Comment by yuzuy** [comment]
@konrin Yes. In detail, refer https://github.com/volatiletech/sqlboiler/issues/576#issuecomment-526716185 and https://github.com/volatiletech/sqlboiler/pull/780
