### ISSUE TITLE
InnerJoin(...) is returning an empty resultset

### ISSUE THREAD

**Issue by frolickingferret445** [volatiletech/sqlboiler#598]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.5.0

And for the record, I am using postgres 9.5 with "github.com/lib/pq" as my postgres driver.

### If this happened at runtime what code produced the issue?

I am new to sqlboiler.  I am trying to do a simple inner join of the clowns and circuses table (schema below).  Each circus has a single clown (but a clown can be referenced in many circuses).  I want an inner join to obtain a circus name with it's clown's name (instead of just the clown's ID).

circusRslts, err := models.Circuses(
		qm.Select("circuses.name", "clowns.name"),
		qm.InnerJoin("clowns ON circuses .clown_id = clowns.id"),
		qm.Where("circus.name = ?", "myexistingcircus"),
	).All(context.TODO(), db)

fmt.Sprintf("%+v` %+v %+v", circusRslts[0].Name, circusRslts[0].ClownID, circusRslts[0].R)

I expected a resultSet to be returned, with my clown's name in the CircusR.Clown object.  Instead, the result set has a single entry, but all values are zeros for integers and empty strings for strings.  My code prints:

` 0  <nil>`
When I run the following SQL query directly on my postgres DB, it works:

`select circuses.name, integrations.endpoint_info, clowns.name from circuses inner join clowns ON circuses .clown_id = clowns.id where circuses.name='myexistingcircus';`

I tried reading the documentation, but there aren't many examples of innerjoins, in my opinion.  The examples don't show how to access the result set from an inner join, and don't show a clear example of how to SELECT columns from the new table.  I tried looking at the comments on the InnerJoin method, but there aren't any.

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

CREATE TABLE clowns (
  id INTEGER UNIQUE NOT NULL,
  name VARCHAR (50) UNIQUE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE circuses (
  name VARCHAR (50) UNIQUE NOT NULL,
  clown_id INTEGER NOT NULL,
  PRIMARY KEY (name),
  FOREIGN KEY (clown_id) REFERENCES clowns(id),
);

**Comment by frolickingferret445** [comment]
I am still seeing this issue after changing my imported driver to:

`_ "github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/driver"`

**Comment by aarondl** [comment]
Hi @frolickingferret445. This is all working as intended (for better or worse). An inner join query mod may be used to help filter, but you cannot access the data from the joined table as a limitation.

There are two ways to do what you would like:
* Custom struct binding
* Eager loading

Custom struct binding is likely the right thing to do here. But it's a bit painful. When you do an inner join in sqlboiler and you want to use the result to populate data, you have to construct and execute your query and `Bind` against a custom object that can use that data. A good example of this is here: https://github.com/volatiletech/sqlboiler#binding in the first code snippet. Although it uses a raw query, you could use a constructed query to do the same. The important part is the renaming of the columns you select to give them a `.` which can help tell `Bind` where to put your data.

The above is a bit more work, but is very efficient. Eager loading is the easier of the two methods, but produces a more inefficient result. See eager loading in the README for how to do that. It's less efficient in 2 ways: It does a separate query because eager loading doesn't understand when it can inner join, and that if you only are selecting a small portion of data (say circus name) it still creates an the full circus object leading to a bigger allocation than necessary.

**Comment by frolickingferret445** [comment]
Thanks, @aarondl .  This was very helpful.

I also recently found your YouTube videos and they were also very helpful!  Great job!
