### ISSUE TITLE
Bind to a struct in eager loading

### ISSUE THREAD

**Issue by sittim** [volatiletech/sqlboiler#618]
My User struct is similar to [AuthBoss](https://github.com/volatiletech/authboss). It has way too much data for most cases when eager loading is performed.  `LoadRelationships()` seems to be the right function, but I cannot figure out how to use it.  So here is what I have:

```Go
// --- this is all the data I need from the user
type SimpleUser struct {
    ID int `json:"id,omitempty"`
    Name string `json:"name,omitempty"`
}

sol, err := models.Solutions(
    qm.Load(model.SummaryRels.User)
).OneG(ctx)

```

How do I make sure that `qm.Load(model.SummaryRels.User)` pulls only the fields spcified in the `SimpleUser` struct?  Specifivally, I am looking for `ID` and `Name`

**Comment by aarondl** [comment]
In non many-to-many cases you can simply add a select query mod inside the eager load:

```go
sol, err := models.Solutions(
    qm.Load(model.SummaryRels.User, qm.Select("id", "name")
).OneG(ctx)
```

This however will not prevent allocation of the full User struct. If this memory usage is concerning enough OR this is a many-to-many query, you'll have to write a raw query due to this issue (https://github.com/volatiletech/sqlboiler/issues/587)
