### ISSUE TITLE
[Feature] NULL-Aware comparison

### ISSUE THREAD

**Issue by soyersoyer** [volatiletech/sqlboiler#619]
I think it could be cool if I can use null-aware comparison in a typesafe way.
Like models.PilotWhere.Name.IsDistinctFrom("John")

https://modern-sql.com/feature/is-distinct-from

What do you think?

**Comment by aarondl** [comment]
I'd have to be convinced of an advantage over what we currently generate.

If today you do: `models.PilotWhere.Name.EQ("John")` this in a type safe way achieves: `"john" == null` will fail as expected. We also generate the `IsNull` and `IsNotNull` helpers to type-safely switch on the null case.

As far as I can tell the article you linked is trying to create a mechanism that will be able drop in any value for either side of the comparison (including null) and it will still work as expected.

If we were to implement the where helpers in this manner, then it would actually become more cumbersome to use since you'll have to create `NullString`s in order to type safely do your equality, as a `string` in Go cannot be `nil`, and therefore a single parameter cannot be either `string` or `nil` without becoming `interface{}` and losing type safety.

Though maybe an argument could be made for comparing to other previously loaded NullStrings from models?

**Comment by soyersoyer** [comment]
In my case, I want to select from a table, where the UserID field can be null.
I want the elements where the UserID is distinct from a specified id, so the where looks like (omit the other conditions):
```
...
qm.Expr(
    models.EventLogWhere.UserID.NEQ(null.IntFrom(user.ID)),
    qm.Or2(models.EventLogWhere.UserID.IsNull()),
),
...
```
I think this is a bit too much code, and the one liner
```
models.EventLogWhere.UserID.IsDistinctFrom(null.IntFrom(user.ID)),
```
is better.

It is only useful, when the field is nullable.

**Comment by aarondl** [comment]
Ok. I understand now.

To refine your statement: This is only useful when you're attempting to do exactly this; look up something where `value` is not `x` OR is null.

This is fine, but I don't believe it needs a where helper. It seems like too odd a use case to be generally helpful and it's of course trivial to write this in a `qm.Where`:

```go
qm.Where(fmt.Sprintf("%s is distinct from ?", models.EventLogWhereColumns.UserID), user.ID)
```

Won't add for now, but if there were enough people who cared then I could be made to reconsider. Thanks for bringing it up for discussion.
