### ISSUE TITLE
Reflection usage

### ISSUE THREAD

**Issue by eyudkin** [volatiletech/sqlboiler#627]
Hi guys!
Thanks for the awesome package.
Just want to ask, why do you use reflection for mappings? I mean, you are generating all structures and queries, you know absolutely enough information to generate typed mapping code for each type.
And thats actually sound logically according to code-generation approach of this package.
Instead of it I can see reflections at binding step which is pretty weird, actually (and all of us know that reflection is a slow, dangerous and etc. approach).

**Comment by aarondl** [comment]
It's an interesting idea and I admit one that I didn't explore. The whole Binding system was made as it is mainly because I wanted to have it in a library and not as part of the generated code.

It's generally useful for binding the results of any generated query on any struct which is good because inner join support requires this.

A side effect of having it in a library away from the generated code is that it can't know about the generated code. Not only from an import cycle standpoint but because it doesn't exist until later.

This is what the whole `L` and `R` on the generated structs are. They're basically anchor points for the `Bind` function to use and do magic.

We could use a similar method to retrieve struct mappings from the struct itself, but this would still require reflection in order to call the method (just like eager loading does now). But then we lose the utility of being able to bind to -any- type, and now constrict ourselves to binding only to sqlboiler generated types unless we use the current reflect-based approach as a fallback strategy.

Overall I'm not convinced that this would be a net gain given that creating the struct mappings occurs one time and then they are cached. And a second caching layer occurs for each set of in/out parameters for a query. This makes this system incredibly fast and I doubt very much that we'd see any true gains in performance from a code-generated approach, but we'd have to measure first.

Not opposed to this, but also not convinced. If you wanted to work on changing the system as a proof of concept with some benchmarking I could provide some support and help with a proposal.
