### ISSUE TITLE
Beginner returns a sql.Tx instead of a Transactor

### ISSUE THREAD

**Issue by muhlemmer** [volatiletech/sqlboiler#641]
Wouldn't it make sense for a `Beginner` to return a `Transactor`?
https://github.com/volatiletech/sqlboiler/blob/e004393fa62ca053ec76d14df63d2e066cd2de23/boil/db.go#L32-L35

Likewise for `ContextBeginner`:
https://github.com/volatiletech/sqlboiler/blob/e004393fa62ca053ec76d14df63d2e066cd2de23/boil/db.go#L56-L59

I'm writing some SQL connection middle-ware, on top of the existing drivers. I also want to be in control of the `tx.Exec` and `Query` variants. This means I can't return a plain `*sql.Tx`, but my own type. That type implements the `Transactor` interface, but I can't return in from my `Beginner` implementation :(

If you agree to this proposal, I will compose a PR.

**Comment by aarondl** [comment]
Typically in Go the advice is to return structs and accept interfaces and that's how this was built. The problem now is that this would be a breaking change and could not happen until v4.

So in the end I don't really have any answers that will satisfy you. Keep in mind that those interfaces are not required for anything as far as I can remember...

**Comment by muhlemmer** [comment]
Yes, as far as I can see my generated models only need `Executor` flavors. So I can have a transaction type which still implements a `Executor` and I probably get away with it.

My models are still relatively simple and I use the `sqlboiler` defaults. So I just want to make sure that I won't be heading into future trouble, in the case methods will need a `Beginner`.

If `Beginner`s and `Transactor`s are not used, perhaps dropping them would be a better fit?

I'm fine with whatever decision and willing to implement if needed, perhaps in the future for v4. :)

**Comment by aarondl** [comment]
They are useful in end user applications and when people use the global syntax. It really does complete the set of interfaces we have even if it doesn't work for your particular use case.

**Comment by muhlemmer** [comment]
@aarondl, I'm not sure if I fully understand your position on this. Please forget my comment about dropping those methods. 

I would like to know if you are okay with a PR that changes the return type to `Transactor`? Or should we put this issue to bed? I'm not in any hurry and fine with waiting for v4. I will take care of re-basing the PR-ed branch against master until you consider the merge can happen (after v4 branch?).

> Typically in Go the advice is to return structs and accept interfaces...

Re: I'm curious where you picked up such advise? Almost every function in the Go landscape returns an interface type: `error`. And there are many standard library functions that return other interface types. `io.Reader` and `io.Writer` interfaces are the first thing that come to mind, like in [`bufio`](https://golang.org/pkg/bufio/#NewReader)

> ... and that's how this was built.

I completely respect that. In every project design decisions are taking using one philosophy or another. And there is no one size fits all solution. So I hope you don't take my comments the wrong way. :innocent:

**Comment by aarondl** [comment]
@muhlemmer hilariously when I searched for a source for this I actually didn't find anything really! I think I may have heard it at Gophercon or on some random talk from there on the internet. It has been a development philosophy I subscribe to by my own logic though:

Any given type *usually* has more methods than any interfaces it implements. If we always return interfaces then we're forced to convert back to the normal type to get access to those. It's therefore less useful in general to return an interface. You want to be specific with what you return so people get as much functionality out of the return as possible. It's of course the opposite when we want to accept parameters, in that case we really want to be as generic as possible so we take a type that is the most generic - or said another way; has the fewest constraints - so as to be as flexible as possible.

You'll notice that actually the sample you linked does not return an `io.Reader` but rather a `*bufio.Reader`, because it's much more useful than an `io.Reader`, despite implementing that interface. The `os` package is another great example of this in `os.Open` or `os.Pipe` etc. All of these could return `io.Writer/Reader/Closer` but return the more useful object `*os.File`.

`error` is a special case because it's really a "reverse-parameter". Most code does not interact with the error directly, it inspects it for nil and throws it up to the level above. In that sense it's kind of passing a parameter to the function above it as a parameter and if the logic above is to be believed it pays to be generic in this case so we can put as many values into that parameter as possible without friction.

So with that logic I returned the `sql.Tx` from it.

In regards to dropping the interfaces I don't really see a need. I use them in my applications when I need to force a Transaction to be used in a method for example and am quite happy with them.

If you are writing a middleware I'd suggest doing so in a way that acts as a database driver as it gives you the access to the internals of the `database/sql` package and then you can set your own type in `driver.Tx` here: https://golang.org/src/database/sql/sql.go?s=55052:56025#L1950 - many other packages have gone this route when implementing DB middlewares because in reality sqlboiler nor any of its interfaces should need to know about your package if it's truly a middleware. Best case scenario that approach would work out of the box with sqlboiler in all ways. Worst case scenario you'd need to to implement an sqlboiler driver to be able to affect generation-time (not run-time though).

**Comment by muhlemmer** [comment]
@aarondl, thanks for taking the time of writing all that. I'm seeing the point now. A valuable lesson.

I've looked to implementing the sql driver interface, but it is to restrictive for my package. Or I still lack the experience / knowledge to do it properly.

Anyway, this issue is not super important for me. I'm just impressed by sqlboiler and would have liked to be able to claim full interface compatibility by my own package. Besides that, I'm fine by opening a Tx separately and passing it as an `Executor` to sqlboiler methods.
