### ISSUE TITLE
Add hook for more primary keys when updating a model

### ISSUE THREAD

**Issue by RichardLindhout** [volatiletech/sqlboiler#645]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Postgresql 10)
MySQL

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler mysql -d

### Further information. What did you do, what did you expect?

I have a database with a lot of organization_id in it where some users only have permission to edit their own organization.

I want to be able to add primary keys to the generated Update functions
```
		cache.query = fmt.Sprintf("UPDATE `block` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, blockPrimaryKeyColumns),
		)
```

In my case what I want is this. (I want organization_id as primary key but not in the database)
```
		cache.query = fmt.Sprintf("UPDATE `block` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, append(blockPrimaryKeyColumns, "organization_id")),
		)
```

Maybe we could provide a hook which adds more columns to the where field e.g.?

**Comment by aarondl** [comment]
It's a very specific feature to your use case and I don't think it's implementation would benefit a majority of users so I don't think this will make the cut.

As for how you can do this see the README section on extending the generated models. You can create an embedded struct that overrides the behavior of the update functions, or you can simply use a function you create that adds `qm.Where` to the query you're creating.

**Comment by RichardLindhout** [comment]
I see, but the update function on my model does not support where. That's what I'd like to see.

**Comment by RichardLindhout** [comment]
I want the end query to be UPDATE block where id = 1 and organization_id=2 without defining all fields as in UpdateAll(models.M{"name": "John", "age": 23}) // Update all rows matching the built query.

**Comment by aarondl** [comment]
@RichardLindhout If you're using `amodel.Update()` then it always updates the model based on the real primary key - there is never a need to add another specifier to it since the job of a primary key is not to do business logic but simply locate records. Your check to ensure org_id matches without being an actual primary key is a form of authorization business logic.

Adding a where statement to an Update also doesn't make much sense because it would cause the update to "miss" updating the target object sometimes. The smarter approach is to never send such an update to the database.

If you're able to use `block.Update` it means block is already loaded into memory. So simply do the check in code.

```go
if block.OrganizationID != userProvidedOrgID {
  return errors.New("unauthorized")
}
```

If you don't or won't have organization_id in memory for whatever reason, I suggest you use raw queries to implement the update that "misses".

If you wanted to keep it in code and REALLY had to have it be generic across all your models you could make this generic by creating some machinery around it that looks something like this (I wouldn't do this myself):

```go
type Updater interface {
  Update(context.Context, boil.ContextExecutor, boil.Columns)
}

func UpdateOrgSafe(ctx context.Context, exec boil.ContextExecutor, u Updater, orgID int, cols boil.Columns) (int64, error) {
    // Use reflect to determine if the passed in updater has a OrganizationID column
    // and do not perform the query if it does not match the passed in orgID
}
```

Another option is for you to create custom templates to implement this functionality in all models that have an organization_id column.

**Comment by RichardLindhout** [comment]
The problem is I don't know if the particular organizationId of the model upfront.

E.g a Block is coupled to organizationId = 4

User with organizationId = 3 tries to update Block.

I would like to prevent doing and extra select query to check if the block is owned by the user.

**Comment by RichardLindhout** [comment]
I don't want really a hook either it would be nice if you could add queryMods to the update query. I think there are use cases where this could benefit users.

**Comment by aarondl** [comment]
That means that you don't have the model loaded and you cannot use `block.Update()` in any way shape or form so your only recourse is to use `models.Blocks().UpdateAll()` regardless of whether or not `block.Update` would support adding a where clause.

I'm not sure why this would be the case (emphasis mine):

> I want the end query to be UPDATE block where id = 1 and organization_id=2 **without defining all fields**

There is no way to avoid specifying all the fields if you're trying to update values. Even with `block.Update()` you need to do the following:

```go
block.Happy = true
block.Update(ctx, db, boil.Whitelist(
   models.BlockColumns.Happy,
))
```

Why is that so different to this:
```go
models.Blocks(
  models.BlockWhere.OrganizationID.EQ(user.OrganizationID),
).UpdateAll(ctx, db, models.M{
  models.BlockColumns.Happy: true,
})
```

Or you could even use a raw query which is made easy by sqlboiler's unobtrusive interface.

As for adding query mods/where clauses to the Update statement the answer is a definite "no" because of exactly what I said before. block.Update() expresses the intent to update that block. It's not conditional (and should not be made to be conditional).

Your requirement is extremely specific and therefore will not benefit the majority of users, keep in mind the age of this library is almost 4 years and this is the first time this feature's been requested. It is also a breaking change to the generated code which makes it even less desirable. There's also many ways to accomplish exactly what you want with little friction so this change won't happen and you'll have to pick one of the solutions presented or come up with something better.

**Comment by RichardLindhout** [comment]
Thanks again for your detailed response and your time!

> Why is that so different to this:
I'm generating the fields the user sends in my graphQL api.
![Schermafbeelding 2019-12-07 om 20 04 25](https://user-images.githubusercontent.com/6492229/70379427-c9049e80-192c-11ea-9e19-7dd4a94417a2.png)



Thank you for this code, I did not really get the UpdateAll interface, but now I do!
```
models.Blocks(
  models.BlockWhere.OrganizationID.EQ(user.OrganizationID),
).UpdateAll(ctx, db, models.M{
  models.BlockColumns.Happy: true,
})
```
