### ISSUE TITLE
Some query mods + eager loading produces invalid memory or nil pointers

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#648]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.6.1

### What is your database and version (eg. Postgresql 10)
11.5

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```go
thingsFromDB, err := models.Things(
                                           // This causes the issue.
                                          //           vvvvvvvvvvvvvvv
    qm.Load(models.ThingRels.SomeOneToOneRelationship, qm.Select("id")),
    qm.Select("id", "name").All(context.Background(), s.db),
)
if err != nil {
    return log.This(c, "error retrieving loans for given year: %w", err)
}
```

### Further information. What did you do, what did you expect?

On queries that return only one thing, eager loading with query mod `qm.Select()`works fine. But if they are meant to return a _slice_, it results in a:

`runtime error: invalid memory address or nil pointer dereference`

**Comment by aarondl** [comment]
I believe this is a problem in to-many use cases (hence "when it returns a slice). The problem is that we enforce a select list. See this issue: https://github.com/volatiletech/sqlboiler/issues/587

I think this is the same problem, different symptom. Going to close as a duplicate. If after looking at that you determine it's a different issue please re-open :)

**Comment by andradei** [comment]
It seems to be closely related and close enough to be a duplicate. I'll subscribe to that issue instead. Thanks.
