### ISSUE TITLE
Logging failed query 

### ISSUE THREAD

**Issue by zamai** [volatiletech/sqlboiler#651]
Hi, 

I'm facing, in my opinion, a pretty common use case : 
 I'd like to log the query statement and it's arguments when it fails. At the moment I only see the error msg like `ErrNoRows`, but I have no context on what was the exact query and its arguments.

I'm aware of the debug option and looking into its implementation I don't have ideas on how to hook into it to **log only** (failed) queries. 

Reading this issue:  https://github.com/volatiletech/sqlboiler/issues/390 suggests that I can wrap the driver itself, but the question remains how can I log only failed queries. 

Example: 
```
ads , err := models.Ads(
	qm.Select(models.AdColumns.ID), qm.Where("created_time > ? ", fromDate.Unix()),		).All(db)
if err != nil  {
// log the query simmilar to debugMode.
//  fmt.Fprintln(logger, qs)
// fmt.Fprintln(logger, args)
	log.Fatalf("error getting Ads: %v", err)
}
```

It would be great if somebody can point me into the direction of solving this, then we can add this example to docs so that other users can use this recipe.

**Comment by aarondl** [comment]
If you wrap the sql driver then you get to intercept calls to all the sql.Exec/sql.Query etc. At that point you should be able to tell when a query fails because it's up to you to return the `err` to the calling code.

I wouldn't be against accepting a way to do failure-based logging in v4 or something. The default must always be off to protect against leaking information into the logs though.

**Comment by zamai** [comment]
Hey, @aarondl thanks for pointing in the right direction.
I was able to get the effect I wanted by creating a wrapper of the SQL driver as you said.

```
// This driver adds SQL query to the message of the error
const driverName = "pg-err-query"

func init() {
	sql.Register(driverName, drv{})
}

type drv struct{}

func (d drv) Open(name string) (driver.Conn, error) {
	c, err := pq.Open(name)
	c = &conn{
		Conn: c,
	}
	return c, err
}

// conn implements a driver.Conn that adds queries to errors, when they occur, otherwise it just calls pq methods.
type conn struct {
	driver.Conn
}

func (c *conn) QueryContext(
	ctx context.Context, query string, args []driver.NamedValue,
) (driver.Rows, error) {
	rows, err := c.Conn.(driver.QueryerContext).QueryContext(ctx, query, args)

	if err != nil && err != sql.ErrNoRows {
		err = fmt.Errorf("query: %s, params: %v: %w", query, args, err, )
	}

	return rows, err
}

// ExecContext adds query to the error message
func (c *conn) ExecContext(
	ctx context.Context, query string, args []driver.NamedValue,
) (sql.Result, error) {

	rows, err := c.Conn.(driver.ExecerContext).ExecContext(ctx, query, args)

	if err != nil && err != sql.ErrNoRows {
		err = fmt.Errorf("query: %s, params: %v, %w ", query, args, err, )
	}

	return rows, err
}
// I only use Context versions, so I only wrapped those 
```
I'm wrapping existing error with a SQL query and its arguments, I find it to be the least disruptive way of adding the query information. 

This approach works, but it feels kinda strange to wrap smth low level (driver), then pass it to generated boil function →  boil.ContextExecutor → back to driver. 

I think the better place would be somewhere near the Debug logging that you have in place right now.
But with the current implementation:
```
if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
```
 I'm not sure what can be the right approach on adding the query information to the errors. 
If you point me in the direction of a possible solution, I'll try to write a PR for it.

**Comment by aarondl** [comment]
Well - you can't just modify the templates to emit the logs if the query returns an error, and then also return that error because that's effectively handling the error twice.

The only thing that might work is to have an error type that contains the query information as well as the underlying error. Of course that query information could *never* be emitted as part of the `Error` interface implementation as that'd easily leak to logs, but you would then be able to convert it to a `boil.Error` and extract the `.SQL` and `.Args` fields from it. That's to say if your application was configured in such a way where it was safe to log these fields, instead of treating it like a generic error you could additionally access the additional information and log it somewhere.

The main problem with this is that some places in the code return `sql.ErrNoRows` and people depend on this behavior currently. So it'd be a breaking change and we'd have to make sure to put it in v4 and show people how to migrate.
