### ISSUE TITLE
Offline code generation given MySQL schema.sql file.

### ISSUE THREAD

**Issue by josdotso** [volatiletech/sqlboiler#657]
I have a schema file generated by MySQL workbench. Can I use sqlboiler without spinning up a live database, by just passing the location of my schema.sql file to sqlboiler?

I looked around for the answer to the above question and haven't found it yet.

Thanks,
Joshua

**Comment by aarondl** [comment]
Hi @josdotso. We do not support offline generation.

We use the database as a source of truth because in order to understand a migration file we would need to parse the contents with 100% accuracy and understand the SQL in the exact same way as mysql does (in regards to creating all the right things etc). Given that SQL varies wildly between implementations (psql, mysql, sqlite3) it would require a metric truckton of work to be able to support all our databases with this approach unless we simply ignored things we didn't understand and supported a very limited subset.

It's not to say it could never be done just that that's why it has never been done. Generally speaking if you're developing an application you're going to have a live dev database somewhere to be able to test with anyway so it doesn't seem like to onerous a requirement.

**Comment by josdotso** [comment]
Thank you. Feel free to close this if you want.
