### ISSUE TITLE
Is there Protobuf generation support?

### ISSUE THREAD

**Issue by mmendez512** [volatiletech/sqlboiler#687]
My team is starting up a new microservice project where we want to generate db models (no doubt boiler can do this) and protobufs (for grpc) from the db schema.

From exploring github, someone mentioned about it in one of the tickets in 2018... That it's possible to "generate file types that are not .go files" such as protobuf and to check the README for the documentation.

But I didn't anything in the current README about protobuf generation. So does such a thing still exists?

Thanks.

**Comment by aarondl** [comment]
There is currently no built-in support for protocol buffers. I think people make their own efforts but none have been publicized that I'm aware of. It's definitely possible, though because I've never heard of any finished implementations I can't be sure that you'll enjoy success without issues along the way.

The ability is still there though. You just have to create your own set of templates and pass them in via the `--templates` option on the command line.

**Comment by mmendez512** [comment]
Okay, thanks for the info @aarondl
