### ISSUE TITLE
Using current_timestamp, updating values

### ISSUE THREAD

**Issue by mgegic** [volatiletech/sqlboiler#688]
Hi! 
We're rewriting our queries using SQLBoiler, and had some problems with a couple of them. The usage seems quite basic, so we're wondering if there's any other way to write them without writing raw queries.

- **accessing current_timestamp**
We have a table with a column for timestamp. We need to make UPDATE and INSERT queries where we want to set the timestamp to current_timestamp of the DB. Is there any way to do it without using raw queries? (we want to avoid using time.Now())

- **Updating/upserting a value**
We need to increase a certain counter by 1, or set it to be 1 if it didn't exist before. Currently, we're doing  `INSERT INTO table AS x (something here)` and specifying
`ON CONFLICT (something) DO UPDATE SET counter_column = x.counter_column + 1;  `
Is there a way to do it using SQLBoiler Upsert as a single query? 

Thank you in advance!

**Comment by aarondl** [comment]
The first (current_timestamp) is just a default value in the database. But the problem is updating it which demands something more heavyweight like a postgresql trigger. In the case where you do use a trigger, the update likely will not understand it needs to fetch a new value, so in sqlboiler you'd have to be quite careful with this. You could potentially use some sqlboiler hooks to help with this.

Note that we have automatic `created_at` and `updated_at` timestamp functionality already but it does use `time.Now()`.

There is an upsert, but there's no way to refer to database-side data in the upsert (`x.counter_column + 1`). So unfortunately that's a raw query.
