### ISSUE TITLE
Any mechanism to control the table for an instance?

### ISSUE THREAD

**Issue by JasonTashtego** [volatiletech/sqlboiler#700]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v3.6.1

### What is your database and version (eg. Postgresql 10)

Postgresql  12.1

### Further information. What did you do, what did you expect?

I have a base schema/table from which I generate code with sqlboiler.  This table is replicated many times over at runtime giving me multiple tables with identical schema.   Is there a parameter at runtime that will control the underlying table that an instance of the model is trying to access?   Or is there a way to accomplish this through other means?  Besides resorting to qm.SQL() to cobble queries together.

**Comment by aarondl** [comment]
Not 100% sure what the issue's about yet with nothing but the description given.

To clear up some terminology: base schema/table as in "normal table inside a schema in postgres", yes?

You mention that it is replicated many times over at runtime. Runtime of what? sqlboiler? Your application?

The last bit of this starts painting a better picture. You have some table `A` and you copy that table's schema to `B` and `C` etc. But you've only generated code for `A` with sqlboiler, and you're wondering if there's some way to control whether a query is targetting A, B, or C?

I'd say that in general sqlboiler doesn't support this use case well at all. The table name is supposed to be a constant that can be referred to (and it is referred to a lot) inside the generated code.

The only way sqlboiler would support this use case in a manner that's not really sketchy is by copying the entire database (like a template database) to a new database name. I assume it's some sort of "this table is for customer X" so instead of that, you copy the database itself to make dbname: "customerX", and you connect to that instance for it.

That's not super nice of course, but I did mention sqlboiler doesn't play well with this sort of model.

If I misunderstood your question let me know :)

**Comment by JasonTashtego** [comment]
You understood my question exactly -- not quite per-customer copies of the table, but multiple copies of the table that are all the same schema -- and this feels like a super common use case in highly scaleable applications. 

We use a custom sharding layer above our tables to balance their growth and allocate space.  This allows us to direct data to new tables as needed and transparently move or copy data between them as needed for performance.

I don't see anything in sqlboiler that would prevent the tablename from being parameterized?  Am I missing something?  

Appreciate your thoughts on this.

Thanks.

**Comment by JasonTashtego** [comment]
And I'd have classified this as a feature, not an issue, but I didn't see a way to do that. ;-)

**Comment by aarondl** [comment]
Hi @JasonTashtego. There's nothing really preventing it other than doing the work, no. I'm not 100% sure how such a feature would look in the current API mind you.

I think as a starting point some custom templates are required to allow for space for a table name. That or some abuse of the `context.Context`.
