### ISSUE TITLE
integrate with .env files

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#711]
We are using .env files to switch between our dev, stage, prod environments.
What I want do is something like:

```bash
#!/bin/bash
source prod.env
sqlboiler
```

and the above would mean - import the environment variables from prod.env and sqlboiler will use those. is there a recommended pattern for doing this?

the best thing I can think of for the moment is, putting this in our .toml file:

```
pkgname = "model"
output = "v1/model"

[fromenv]
dbname = "$cp_pg_db_name"
host = "$cp_pg_host"
user = "$cp_pg_user"
```

and then using:

```bash
#!/bin/bash
source prod.env
sqlboiler fromenv
```

but I get the feeling that won't work since I am not sure if custom env vars like the ones I used in the .toml file are supported?

**Comment by aarondl** [comment]
sqlboiler should never be targetting a production database. It is a development-time code generation tool only and as such there's no reason to target anything but a development database (which is why there's no split environments in the config file from the beginning).

As for supporting env files I suggest you look into `direnv` which can help out here.

**Comment by mg98** [comment]
That makes sense. It is good to work with env files to support different environments on the local machines of the developers though.

I haven't heard of `direnv` before. But from what I read it is just a tool to set environment variables in a `.envrc` file. And I think the question of this issue was how can we insert environment variables into the config file of sqlboiler?

Thank you.

**Comment by aarondl** [comment]
There is no way to insert env vars into the config file of sqlboiler without some custom software that you would write. I recently rewrote the environment variable portion of the readme which may help you out.
