### ISSUE TITLE
Why "reflect"ion?

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/sqlboiler#713]
I'm new to sqlboiler: in love with it from months, played with it first time today.

I read in Readme this:

> Being Go veterans we knew the state of ORMs was shaky, and after a quick review we found what our fears confirmed. Most packages out there are code-first, reflect-based and have a very weak story around relationships between models.

and I was immediately happy.

But soon after first generation I saw the monster: `import "reflect"`!!! ☠️ ☠️ ☠️ ☠️

Strange for a `database-first code-generation approach`.

Am I wrong?

Can I ask you why?

**Comment by aarondl** [comment]
The idea is that a large portion of the code is code-generated as opposed to query built using reflection. This means that your database types are represented properly everywhere as well as in methods such as `FindUser` where you'll see the proper type for your primary key (not an `interface{}`).

Reflect however is a necessary evil to be able to bind a variable-length query to a struct (or to do eager loading). Because we do not know what columns you want in any given `select` statement we must use reflect under the hood.

To be able to respond to a large amount of queries without generating functions like: `SelectID`, `SelectIDAndName`, `SelectIDNameAndAge` we use reflect where absolutely necessary.

Hopefully that answers the question.

**Comment by frederikhors** [comment]
Thanks, I'm not an expert.

Just to understand: can you generate all the parts we now use with "reflect" or is it impossible anyway?

And the disadvantages of generating everything (even the functions you are talking about)?

**Comment by zikaeroh** [comment]
In general, all of the code that's reflection based is related to binding, i.e. mapping data returned by queries back onto the original objects. You can't just pass a model into `db.Query` and it work; you have to pull out a row and extract the resulting columns.

If SQLBoiler is to support binding in general (i.e. support one-off anonymous query result types) without generation, then it has to go through reflection as there is no schema from which those types could be generated. At that point, the code exists to do the binding in that form, and trying to generate it again in another place (entirely new all-static implementation) would be a maintenance burden. Imagine improving the performance of the reflection based binding code, then having to re-do that work again in the templates.

The only thing being saved if this code were to be fully generated is the binding speed, which I'm not convinced is always the slowest path anymore for known types now that my cache key performance PR has been merged. I've even found cases where going the "unsafe" way (raw query with a raw bind) is faster than the type safe stuff anyway. And, at some point the database/network speed ends up being the bottleneck, not whether or not reflection/generation was used to say, figure out the column name for a given field.

I get the philosophical principal that "if it can be code genned, it should not need reflection", but there's diminishing returns for a lot more effort and I personally think it's in a good place.

This isn't to say that all code gen is bad because it takes more effort; there are certainly code generators out there which do a great job in their specific domains, like EasyJSON for statically generating JSON marshaling code.

**Comment by aarondl** [comment]
Thanks for fielding this @zikaeroh :)
