### ISSUE TITLE
Generated code keeps refering to v4 and v8 folders when they do not exist

### ISSUE THREAD

**Issue by GraciousGpal** [volatiletech/sqlboiler#743]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.1.1

### What is your database and version:
Sqlite3

### If this happened at generation time what was the full SQLBoiler command you used to generate your models?
```
sqlboiler sqlite3 -c ../lib/sqlboiler.toml --no-hooks
```
###
Several imports generated that points to non existing folders:
github.com/volatiletech/sqlboiler/v4/boil
github.com/volatiletech/null/v8

This was easily fixed by refracting "/v4" and "/v8" out to get it to work. But it is annoying having to refract it every time the model is changed
The library was installed using the commands stated in the Github page.

**Comment by DylanJ** [comment]
I also have this issue.

**Comment by aarondl** [comment]
This sounds like you have not updated and re-installed the sqlite3 driver. Can you confirm?

**Comment by dotmartyr** [comment]
I'm having this issue as well, after a full delete and reinstall of sqlboiler and the psql driver.

**Comment by GraciousGpal** [comment]
I have reinstalled, the problem persists

**Comment by vitroz** [comment]
Im also having this problem, using postgres on v3.7.1
Tried updating the driver by running `go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql`

**Comment by mauleyzaola** [comment]
This has worked for me, hope same for others having the same issue:
* Remove all binaries from `$GOPATH/bin/sqlboiler*`
* Download latest binaries
```
export GO111MODULE="on"
go get -u -t github.com/volatiletech/sqlboiler
go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
```
* Use regular package references in the code
```
github.com/volatiletech/null
github.com/volatiletech/sqlboiler/boil
```

imo it makes no sense versioning if the latest is working great

**Comment by aarondl** [comment]
Okay. I think I have an inkling as to what's going on here.

The v8/v4 folders are semantic import versioning folders. They exist to declare that it's part of a major version of a package. This is part of the Go modules system described here: https://blog.golang.org/using-go-modules

sqlboiler v4 moved to the Go module system. This is the Go dependency management system and was introduced in Go 1.11. We're years after that and I made the decision that sqlboiler should be a Go module now that the problems with modules have started to smooth out.

You will encounter issues with sqlboiler v4 if you do not have a Go version that understands semantic import versioning. If you are +1'ing on this issue here please include some details:

* What is your Go version?
* What is the output of `sqlboiler --version`?
* What is the output of `go env | grep GO111`?

I believe Go versions <1.10.4 and <1.9.7 have no idea how to deal with semantic import versioning and will simply not be able to use sqlboiler anymore. There is no support for these versions of Go neither in the Go community nor in sqlboiler, please upgrade Go if you find you have an old version of it.

In order to ensure everything works:
* Make sure you delete all `sqlboiler-*` binaries
* `go get` the binaries in a "module-friendly" way. This prevents Go from thinking you want to add this module as a dependency to your current package and does the correct behavior from older versions of Go. See this issue for more details: https://github.com/golang/go/issues/30515

```shell
env GO111MODULE=off go get github.com/volatiletech/sqlboiler
env GO111MODULE=off go get github.com/volatiletech/drivers/sqlboiler-psql
```

This should leave you with the latest sqlboiler and sqlboiler-psql, and it should generate code with v8/v4 in the paths, and as long as you have a Go version that understands semantic import versioning it -should- work.

**Comment by shodgson** [comment]
Thanks for the helpful explanation. @aarondl , I believe you meant to suggest having GO111MODULE **on** as @mauleyzaola mentioned:
```
env GO111MODULE=on go get github.com/volatiletech/sqlboiler
env GO111MODULE=on go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
```
(Note also the slight difference in the sqlboiler driver path)

**Comment by aarondl** [comment]
Hi @shodgson. I have updated my comment to have the correct drivers path. Thanks for pointing that out. However the suggestion that GO111MODULE should be *on* is definitely incorrect. We're attempting to get old `go get` behavior. We don't want modules on for that. If you wanted to have the modules on for your `go get` you'd have to include the `v4` in the version path for starters, but if you look at the issue you'll see that there's still no good way to get a binary at a specific version in Go (that I know of).

What I suggested gets you the latest version of the binaries on master.

**Comment by shodgson** [comment]
I could only get it working with GO111MODULE on. Maybe because I was in
GOPATH?

**Comment by aarondl** [comment]
@shodgson I'm not sure. Perhaps you could try again later and we could understand better why that didn't work for you.

**Comment by julvo** [comment]
Hey @aarondl,
I ran into the same issue today, but solved it by migrating my project to using Go modules. Just want to report it here, to provide more info that could help to solve the issue for others.

In my case, my project was located in GOPATH/src and not using Go modules. After removing the old sqlboiler binaries from GOPATH/bin I updated sqlboiler using the commands suggested above:
```
GO111MODULE=off go get github.com/volatiletech/sqlboiler
GO111MODULE=off go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
```
Then, after running `sqlboiler psql --wipe`, the generated files included version-aware imports, e.g. `github.com/volatiletech/sqlboiler/v4/boil`. During the build, to compiler complained that it couldn't find all packages, where the import included the version.

I'm not sure whether it is possible at all to use version-aware imports in GOPATH/src without using modules. If it isn't, then it could be a good option to add an option to make sqlboiler generate version-agnostic imports. If it is possible to use version-aware imports from Go modules inside non-module projects in GOPATH/src, then I don't know what causes the issue.

Here are my version numbers:
```
go version go1.14.4 darwin/amd64
SQLBoiler v4.1.2
GO111MODULE="" (also tried setting this to 'on' and 'off')
```

**Comment by aarondl** [comment]
Hi @julvo, you're right. But the idea of v4 wasn't to preserve compatibility it was to break it (hence v4 instead of continuing on v3).

v3 is no longer maintained but you can continue to use it. But go modules is the future whether we like that or not and as good citizens in the ecosystem we should be adopting it. A lot of the big problems with it have been ironed out and although the `go` tool's implementation of module-aware commands is still unbelievably bad, compiling/managing versions etc all works quite well.

The reason you use the commands I showed above to download the binaries is to ensure if you're accidentally in a go module (like your project's directory) you don't add an old version of the dependency which is what the `go` tools atrocious design will have you doing if you use `go get` even on a binary package. See this issue https://github.com/golang/go/issues/30515 I linked earlier.

**Comment by aarondl** [comment]
I have updated the readme to have better installation instructions and reflect the fact that v1, v2, v3 are no longer maintained, and that v4 is not GOPATH compatible (you must use go modules if you intend to use a maintained version of sqlboiler).

**Comment by julvo** [comment]
> I have updated the readme to have better installation instructions and reflect the fact that v1, v2, v3 are no longer maintained, and that v4 is not GOPATH compatible (you must use go modules if you intend to use a maintained version of sqlboiler).

This will be very helpful for people like me trying to use v4 in GOPATH projects - thanks for adding this.

Also just wanted to say thank you for your great work. I'm a big fan of sqlboiler and the approach of generating code from db schemas rather than the other way round.

**Comment by aarondl** [comment]
@julvo Thanks for the kind words :) I do encourage you to move to Go modules. There are a number of advantages over GOPATH. Even though I hate the tooling for it, modules are a much better system in almost every way.

**Comment by chochihim** [comment]
I am quite against the usage of "global install" tools as it is hard to ensure that our team members use the same version. We always break the code due to using different versions of the tools. 

Go modules solves this problem, because we can now specify the version we use in a project. I will share how we manage to use `sqlboiler` (both command line utility and project dependency) locally:

1. Install `sqlboiler` with Go modules according to existing README instruction:
```bash
# Do not forget the trailing /v4
go get github.com/volatiletech/sqlboiler/v4
# Assuming you're going to use the null package for its additional null types
# Do not forget the trailing /v8
go get github.com/volatiletech/null/v8
```
2. Install the driver
```bash
# Install an sqlboiler driver - these are seperate binaries, here we are
# choosing postgresql
GO111MODULE=off go get github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql
```
3. Go to `GOPATH/bin` and find your driver binary. In our case, it is named `sqlboiler-psql`. Move this binary to your project root.

4. It's done. We have installed `sqlboilder` locally: the project dependency is declared in `go.mod`, while the driver binary is placed at root directory. Both are to be put in your git so we have version control on them. Whenever you need to run `sqlboilder` as command line tool, use `go run github.com/volatiletech/sqlboiler/v4 psql`. It uses the binary in your project root. You can also use `//go:generate go run github.com/volatiletech/sqlboiler/v4 psql`.

**Comment by wych42** [comment]
Install as READMD don't work with mysql driver.

```
: cannot use dialect (type "github.com/volatiletech/sqlboiler/v4/drivers".Dialect) as type "github.com/volatiletech/sqlboiler/drivers".Dialect in argument to buildUpsertQueryMySQL
```

Environment:
```
go version go1.13.8 darwin/amd64
SQLBoiler v4.2.0
GO111MODULE="on"
```

sqlboiler v3 would be downloaded and added to go.mod on install:
```
$ go get github.com/volatiletech/sqlboiler/v4

go: extracting github.com/volatiletech/sqlboiler/v4 v4.2.0
go: extracting github.com/volatiletech/sqlboiler v3.7.1+incompatible
go: extracting github.com/volatiletech/strmangle v0.0.1
go: extracting github.com/volatiletech/inflect v0.0.1
```
