### ISSUE TITLE
Missing testdbname should imply false skipsqlcmd

### ISSUE THREAD

**Issue by sanketplus** [volatiletech/sqlboiler#753]
Currently, sqlboiler gives the power to leave out `testdbname`. So in this case a random db will be created. At the same time, user can set `skipsqlcmd` option to false and in that case foreign keys are not dropped.

If the schema contained foreign keys, the randomly filled structs during tests will violate fk constraints and tests will fail naturally.

Also, I think it is implied but just wanted to confirm that sqlboiler cannot tests schemas with fk constraints without dropping them, right?

Happy to raise a PR for a fix. Least we can do is at least document these options and its implications (which are missing from the table at the moment)

**Comment by sanketplus** [comment]
If this is true
> Also, I think it is implied but just wanted to confirm that sqlboiler cannot tests schemas with fk constraints without dropping them, right?

Shouldn't `FKeyDestroyer` always run? regardless of user given db or auto generated.

**Comment by aarondl** [comment]
The fkeydestroyer should probably always run. I'm really not concerned about the tests not functioning correctly as I've said elsewhere. They barely work for anybodys database because of constraints anyways.

And yes the tests cannot run with foreign keys on, because the tests don't avoid running isolated actions like insert/delete/update for single models, even if there are fkeys that would prevent -just- that model from being inserted.

If a user gives us a DB, we don't want to be dropping the foreign keys from it. So the decision was made not to affect their DB with any DDL statements, only run the tests, useless as that may be.

**Comment by sanketplus** [comment]
Thanks @aarondl for getting back. I get it, tests, apparently, will most likely fail because of the way they work with given DB constraints.

I feel at least we can document this behaviour. As a first time user, it was weird to have tests fail on fk constraints. Had it been documented somewhere, that'd be a lot helpful and would have saved quite some debuggin time.

**Comment by aarondl** [comment]
@sanketplus I have added a readme bit to the FAQ:

https://github.com/volatiletech/sqlboiler/#why-are-the-auto-generated-tests-failing

Hopefully that's sufficient.

**Comment by sanketplus** [comment]
much thanks @aarondl 🙌
