### ISSUE TITLE
How to get a table name from the generated model?

### ISSUE THREAD

**Issue by righ** [volatiletech/sqlboiler#755]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.4.0

### What is your database and version (eg. Postgresql 10)
MySQL 5.7.29

### Question
How do I get a real table name from the generated model?
I could not find the feature and It seems newer version also does not provide it. (probably)

I think it would work if I add the following code to templates. Is this the right thing to do? 

```go
func (_ {{$alias.UpSingular}}) GetTableName() string { return "{{.Table.Name}}" }
```

Also, I want it to be supported as standard. if I make the PR here, is there a possibility that you accept it?

**Comment by Darkclainer** [comment]
I think what you want is presented in `singleton/boil_table_names.go.tpl` template. 

This correspond to `boil_table_names.go` generated files. There is var `TableNames` where all table from your schema are present.

**Comment by righ** [comment]
Thanks for your reply.

`TableNames` surely have all names as you said, but it is related to not singular name and it can not be retrieved from the model. Let me know if you know the way to get a name from specified model using the `TableNames`.

For example, if I have a `jets` table and a `Jet` model.
I want a name `"jets"` in the following way:

```go
jet := Jet{ID: 1}
tableName := jet.GetTableName()
// use the table name
fmt.Println("ID:", jet.ID, "table:", tableName)
```

**Comment by Darkclainer** [comment]
Hm, I have misunderstood what you want. I don't think sqlboiler have a builtin capability to do what you want.

Also I think your idea to include additional method in the template is perfectly OK, I have done this too for validating user's request (if a requested column exists for speicified table/model?). But be aware that adding your custom template is not very "neat" solution, because you will need to copy all original templates (remeber that you need to bother with versions) somewhere, specify them and your additional template folder with `--templates`. I have done this through building special docker container, than moved to my own fork of sqlboiler (because I have needed changes beyond templates). 

I don't know if your request will be accepted or not, but I think we can do best, if we will provide an easier way to specify additional templates (without removing original ones). This is not very easy to implement, but I think it can be worth it.

**Comment by righ** [comment]
In fact, I don't want to handle it with custom template for that reason.
Because our project is working in go modules mode, it is hard to get the standard template paths for each  environments. And I do not want to make a directory copy.
So I agree with your suggestion. I'll make the option when I have much time.

Though I think the easiest fix for my request is adding `GetTableName()` method into standard template (e.g. 00_struct.go.tpl) at the moment.

Anyway I found out there is not what I want yet and my response was not wrong.
Thanks a lot.
