### ISSUE TITLE
Proposal: make generated query struct exported

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [volatiletech/sqlboiler#766]
Hi, probably this was already discussed before, but i didn't found anything related. Basically, i want to write code similar to this:
```
var userCountQuery models.userQuery

if something {
    userCountQuery = models.Users(qm.Where("something=?", "something"))
} else {
  userCountQuery = models.Users(qm.Where("another_something=?", "something"))
}

userCountQuery.Count(...)
```

But, of course i can't do that, because `userQuery` isn't exported. I know that i can do something like this as a workaround:
```
var mods []qm.QueryMod

if something {
    mods = append(mods, qm.Where("something=?", "something"))
} else {
    mods = append(mods, qm.Where("another_something=?", "something"))
}

models.Users(mods...).Count(...)
```

But still, wondering why generated query struct isn't exported is there any reasons for that?

**Comment by aarondl** [comment]
The generated query struct isn't exported as it's generally not considered useful and is more spam to see in the documentation. We try to keep what's exported so the surface area of the API of a generated package is digestible.

Because there's an easy workaround that's documented in the README already I'll close this with no action.
