### ISSUE TITLE
insert conflict - how to test for corresponding error

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#783]
I am working with postgres.
There are 3 error types on the sql package:

![Screenshot from 2020-06-26 13-29-08](https://user-images.githubusercontent.com/11139560/85898396-0a697800-b7b1-11ea-84a4-04a315cbf4bd.png)

what I am trying to do is determine if the error correponds to an insertion conflict or if it's some other type of error.

![Screenshot from 2020-06-26 13-28-15](https://user-images.githubusercontent.com/11139560/85898440-1ce3b180-b7b1-11ea-8d62-2c9eca88e225.png)

How will I know if I should respond with an http 409?

thank you

**Comment by aarondl** [comment]
Use `errors.Cause` from the github.com/friendsofgo/errors package to retrieve the completely unwrapped error. This will be a [pg.Error](https://pkg.go.dev/github.com/lib/pq?tab=doc#Error) and you can type assert to figure out what actually happened inside postgresql.

I attempted to use `errors.As` from the friendsofgo/errors package very recently and found it did not work. I am not sure why but it was quite frustrating, so I had to resort to using errors.Cause so that's the path I recommend.
