### ISSUE TITLE
[Feature] Dry run mode

### ISSUE THREAD

**Issue by crlssn** [volatiletech/sqlboiler#794]
It would be neat if there were a flag you could set like `boil.DryRunMode = true` that would not execute any `insert`/`update`/`delete` commands and instead print out the rows that would have been modified.

**Comment by stephenafamo** [comment]
I think this is best done with the `boil.ContextExecutor` that is passed to the `Insert()` `Update()` and `Delete()` methods.

You can use an interface that prints out the queries and their arguments, or if there was a database dry-run driver implementation that you can pass instead.

Since SQLBoiler **ONLY** interacts with the database through the executor, it feels like trying to do this at the ORM level is not the right place.
