### ISSUE TITLE
[question] is there has another default simple ways to mapping json response

### ISSUE THREAD

**Issue by cacing69** [volatiletech/sqlboiler#806]
i have a create custom stcruct 

![image](https://user-images.githubusercontent.com/36250619/88464692-067f6180-cee7-11ea-9487-7059ea52cb37.png)

to make response like this

![image](https://user-images.githubusercontent.com/36250619/88464663-dc2da400-cee6-11ea-833a-5bd9a7ca9dd1.png)

is there have a another simple ways to make a custom nested response like that?

**Comment by aarondl** [comment]
In my own projects I've created a reflect-based mapper function to map from my sqlboiler models to my response structs. I need this generally because sqlboiler structs are not 1-1 with response structs. The other thing you could consider is just creating a function per struct-pair to be converted. `SQLUserToJSONUser` or some such thing. This way you keep the type safety, but pay in boilerplate. But the approach is definitely less magical.

There is no other way to map things to your own json-like objects except by extending sqlboiler with custom templates & data so I will close this issue.
