### ISSUE TITLE
Question:  Generate models from static .sql files

### ISSUE THREAD

**Issue by jay-manday** [volatiletech/sqlboiler#863]
I have a question, my company has been really excited by SQLBoiler, we recently integrated it into a new product we're working on and have been impressed by the results and productivity. However we wanted to avoid having to commit the autogenerated models, we have an existing migration tool for `postgres` (alembic/sql alchemy unfortunately) which, thankfully can export static .sql files. 

The crux of my question is this, can sqlboiler generate models and such from static .sql files, thereby removing the need for a db connection at build time? This would be a huge win for us if we can do that, I've been reading over the docs but wanted to post the question here.

Thanks again,

-J

If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`github.com/volatiletech/sqlboiler/v4 v4.3.0`

### What is your database and version (eg. Postgresql 10)
`postgres 11.7`

**Comment by aarondl** [comment]
Hi there Jay. Glad you're enjoying it.

> However we wanted to avoid having to commit the autogenerated models, we have an existing migration tool for postgres (alembic/sql alchemy unfortunately) which, thankfully can export static .sql files.

This is pretty contrary to the way it's designed to work (not committing the models). Early on we made the design decision that it's easier to ask the database about the database rather than attempt to understand the entire DDL dialect for every database engine we support and generate models from that.

I also recommend you check in the models because that generated code is required for your program to function. Generated code is just Go code written in another language, but is still required for your program to compile and run just like a source file you wrote by hand. It's my personal philosophy that Go repositories should be `go build`-able post clone without any additional steps but perhaps you have other tradeoffs you're looking at that makes it unfeasible or less appealing.

In general the workflow is supposed to look like this:
* Developer creates sql migration
* Runs migration tool & generates sqlboiler models (usually in the same build script step)
* Developer codes with new database things
* Developer checks in ALL code (migrations, updated models, his code)

If none of this gels I can recommend sqlc to you as an alternative which uses .sql files as a way of generating models. Though my recommendation of checking the generated code into the repository would stand even if you switched tools.

Hope that helps.

**Comment by jay-manday** [comment]
Sorry for the belated reply! Thanks for answering my question I really appreciate it.

**Comment by raphoester** [comment]
I have just created a simple boilerplate to easily generate the boiler code from static sql files : https://github.com/raphoester/sqlboilerplate
