### ISSUE TITLE
chan limit for concurrent requests to be

### ISSUE THREAD

**Issue by ORESoftware** [volatiletech/sqlboiler#879]
I am wondering if this exists already in the library or if it would be useful, something like:

```golang
package limiter

var c = make(chan int, 500)

func Run(x func()){
  c <- 1
  x()
  <- c
}

```

it would limit the number of concurrent db requests to 500 here? any benefit? does the library do this already? it would probably have to be internal to the library, otherwise would be too cumbersome to deal with.

Not sure if there is any value here though, just curious.

**Comment by aarondl** [comment]
This library knows nothing about concurrency. It's all up to the driver and the application software. We definitely don't want to be supporting any of this as it's all doable nicely outside this lib for now.

Generally I think this can be controlled by how many connections you allow to the database in the pool inside your db.SQL since that would be the limiting concurrency factor.
