### ISSUE TITLE
Add version checking ability to generated codes

### ISSUE THREAD

**Issue by mmohaveri** [volatiletech/sqlboiler#925]
I'm using sqlboiler to write a service that is responsible to sync changes coming from an other database from a queue.
Each entity has a version, and I'm only supposed to apply the message to the database if the version of the message that I have is newer than version of the message in database.

Currently I have to write a manual SQL INSERT/UPDATE query for all of my entities as I'm not able to change the generated SQL command for Insert and Delete and the Hooks are not the solution as I want the whole version management to be handled by the database as it reduces risk of inconsistency with the least overhead.

Can we add a mechanism for that? for example a template that I give to the sqlboiler command that changes its generated SQL codes.

What I mean by version checking mechanism is something like this:
```sql
INSERT INTO users (id, version, username, name)
VALUES ("id from message", "version from message", "username from message", "name from message")
ON CONFLICT ( d) DO
UPDATE SET version="version from message", username="username from message", name="name from message"
 WHERE users.version < "version from message"`,
)
```

**Comment by aarondl** [comment]
It's very unlikely that we'll add this to sqlboiler because it's extremely specific to your particular use case of a database. If you wanted to attempt to convince me that many people would benefit from this and that it should be included the following steps would need to be taken:
1. Gather evidence showing that this is an industry best practice and many people are using this pattern
2. Put together a thorough proposal as for how it would be implemented in sqlboiler

That's a decent amount of work so here are some other solutions which are much easier:
1. Forking the templates with sqlboiler is easy and supported by the cli arguments/config of the tool. You could simply add this to the templates yourself and keep it for your own project.
2. You could create a package that sits above your `sqlboiler` generated models package (which you likely already have) and just create proper wrappers at that level that will do the correct thing.

If you would like to submit a proposal feel free to re-open this issue.
