### ISSUE TITLE
types.JSON fails to marshal when field is not selected

### ISSUE THREAD

**Issue by jakecoffman** [volatiletech/sqlboiler#926]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

4.5.0

### What is your database and version (eg. Postgresql 10)

Postgres 12

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

Repro here https://github.com/jakecoffman/sqlboiler-tests/blob/4b16d6d7f22a4526d01fa258f854ed0bdf46adce/main.go#L53

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

See repo above

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

See repo above

### Further information. What did you do, what did you expect?

Since the `jsonb` column is `not null` it generates `types.JSON` since it can't be null... however it can be null if the field is not selected and this marshaling fails. 

I'm thinking the simplest solution is to add `omitempty` to the json tag.

**Comment by aarondl** [comment]
Wondering about how to fix this. `omitempty` is problematic because it omits zero values for some reason which is a change in behavior and a sneaky one we don't want to force on people. It'd have to be some sort of option.

The reality is is that the models aren't -really- intended for jsonification and I've always advised using a set of separate structs for an API since the models will never really match up perfectly with what you need/want in an API and there's no ability to customize them (like you're needing right now).

If you have a non-nullable `JSON` field it does seem like an invalid state for it to be in to not have any json data and so marshaling something invalid to JSON shouldn't work. I think the best thing to do in all cases here is just use a custom struct or simply give it a value before marshaling like `{}` or `null` or what have you.

If you -really- want to I could probably be talked into having the omitempty flag be an option somewhere. I kind of thought there was a way to do this already but maybe not.
