### ISSUE TITLE
Support for model validation

### ISSUE THREAD

**Issue by n3integration** [volatiletech/sqlboiler#93]
First off, thanks for **sqlboiler**! It's been a huge timesaver for our team. 

Although, there may already be a defined pattern for handling this w/ sqlboiler, how best should model validation be handled? We would like to validate our models up front in our request handlers. Is it feasible to auto-generate validation struct tags based on the schema definition (e.g. [go-playground/validator](https://github.com/go-playground/validator/tree/v8.18.1))? 

If you're interested in this as a core capability, we could take a stab at it and submit a pull request.

**Comment by aarondl** [comment]
Very glad to hear people are using it successfully (or I hope successfully!).

I think validation could be generated and have a place in SQLBoiler but I would put in a vote for a much more unobtrusive approach. A library that takes validation out of the struct might be nicer: https://github.com/kat-co/vala - it also opens up the options for people to later add more validation as they see fit without having to change the struct further. Consider the use case where the generation is not enough, users still don't have the ability to modify the struct directly and therefore they'd be unable to set any extra validation requirements that the inference didn't pick up.

Thoughts on this?

**Comment by nullbio** [comment]
@n3integration Hello. Also just wanted to add that we added hooks as a means of validation as well: https://github.com/vattle/sqlboiler#hooks -- Not sure if this fits your model, but figured I'd mention it just in case.

**Comment by n3integration** [comment]
@aarondl - I completely agree that there would be too many cases that cannot be predicted up front from the schema alone. Many times users would still be required to write their own validation logic, so it makes sense to provide an extension point to provide custom validation. What are your thoughts about something similar to the following? 

```go
func (m *Model) BindJSON(reader io.Reader) error {
    if err := json.NewDecoder(reader).Decode(obj); err != nil {
        return err
    }
    return Validate(m)
}

func (m *Model) Validate() error {
    ...                           // 1. Perform generated validation
    OnValidate(m)                 // 2. Perform custom validation, if hook is registered
}
```

@nullbio - Thanks for the hook pointer. A custom validation hook might be a good extension point.

**Comment by aarondl** [comment]
I've been thinking more about this problem. I'm wondering how far ahead a user would truly get by using generated validation. One of the biggest problems being the errors that are generated from this stuff may need to be i18n'd and translated.

I can imagine a scenario where the error messages only serve English users well. And then everyone else would have to be able to have access to some sort of "pluggable" system to translate the errors into their language and that brings all kinds of fun.

So I guess questions to be answered in order to move forward are:
- How insufficient are the current hooks at providing validation?
- How much boilerplate could we truly save (considering error messages must be provided by the user)?

**Comment by n3integration** [comment]
@aarondl - i think that [ozzo-validation](https://github.com/go-ozzo/ozzo-validation) may be a good way to go to support validation within sqlboiler. thoughts?

**Comment by aarondl** [comment]
Yeah, it looks very nice to me. Looks like a souped up Vala.

**Comment by aarondl** [comment]
Not going to leave this opened as it won't be added unless someone opens a PR for it.

**Comment by tooolbox** [comment]
> How insufficient are the current hooks at providing validation?

One problem with using hooks for validation is a point of consistency.  Ideally you would write the hook once and have it Just Work™, meaning thereafter your actions will always be validated.

With the current hook mechanism, you have to import your models and call `models.AddSomethingHook()`.  If you're using these models in multiple packages, you have to remember to call `init()` and register the hooks each time, or make your own `hooks` package and import it to trigger the registration.

I thought of somehow adjusting the SQLBoiler settings to generate import statements to a non-generated package that would then add the hooks (thereby forcing their registration whenever you import the models) but that creates an import cycle.  To achieve "global validation hooks" in a type-safe fashion, they would need to reside in the generated `models` package.

I would suggest some sort of `hooks.go` file that is part of the `models` package but not auto-generated, so you can put the hooks there, but I have read elsewhere your opinion on this.

This could be done through settings in your config file, using the whole column-matching mechanism, and then something like [`ozzo-validation`](https://github.com/go-ozzo/ozzo-validation) (as mentioned) for the validation...but it's not terribly exciting.

This particular problem is a result of making the data-representation package also do the manipulation, and making this package auto-generated.  (Not a criticism really, just an examination of tradeoffs.)

One thought is that, since the database is treated as the source of truth, maybe it makes sense to put the data validation rules in the database, a la `CHECK` clauses.  That might be a decent official stance, given that there is currently *not* an official stance, although I'm not sure how versatile this route is.

**Comment by tooolbox** [comment]
One other way to do this is to use a custom type with your own `driver.Valuer` implementation.  You can do some per-field validation this way that will Just Work™ although you might cause the acceptance tests to explode.

**Comment by aarondl** [comment]
You're right that if you want validation to be part of the models package, there is literally only the option to keep it in the same package. And also correct that that sort of idea is frowned upon by us.

> With the current hook mechanism, you have to import your models and call models.AddSomethingHook(). If you're using these models in multiple packages, you have to remember to call init() and register the hooks each time, or make your own hooks package and import it to trigger the registration.

There's a few oddities in this paragraph:

1. `init` is a magic Go function and is called automatically, and does not need to remember to be called. Only the import of the package containing the init does. Typically a `modelsx` (models extension package) is a perfect place for this.
1. `models.AddXHook` affects the global memory of the `models` package, that's to say it doesn't matter how many packages in a binary import `models`, if at ANY point in any package inside that same binary you've called `models.AddXHook()` the hook is now being called by all packages in that binary so the hook registration is not a per-package TODO, but a per-program todo which is slightly better.

The way I recommend doing this to utilize the above correctly is: Use a `modelsx` package to extend your models with extra helper functions AND an `init` function that registers all your validation hooks. At the top of your main / the place where you side effect import your database driver (eg `lib/pq`) also side effect import the `modelsx` package so you can now be sure that the entire program has the hooks registered.

If in the unfortunate event you forget to import `modelsx` for the side effects at some hierarchically high-up file, it's almost certain that you've accidentally imported it in order to use it for other helpful functions and the same result is achieved.

It is not fail-safe unfortunately, but I also don't think it's -that- bad or error prone given you only have to do this once per program.

Also FWIW I also use check clauses because I can't be sure that only Go clients will ever talk to the database and at least some basic validation should still be used.

**Comment by tooolbox** [comment]
> init is a magic Go function and is called automatically, and does not need to remember to be called. Only the import of the package containing the init does. Typically a modelsx (models extension package) is a perfect place for this.

That thought came out scrambled.  I meant "call `Add` to register the hooks in the `init()` of each package".  I don't know if that mistake quite merited having `init()` explained to me slowly and carefully, but I apologize for the confusion.

> models.AddXHook affects the global memory of the models package, that's to say it doesn't matter how many packages in a binary import models, if at ANY point in any package inside that same binary you've called models.AddXHook() the hook is now being called by all packages in that binary so the hook registration is not a per-package TODO, but a per-program todo which is slightly better.

This is a good point!

> The way I recommend doing this to utilize the above correctly is: Use a modelsx package to extend your models with extra helper functions AND an init function that registers all your validation hooks. At the top of your main / the place where you side effect import your database driver (eg lib/pq) also side effect import the modelsx package so you can now be sure that the entire program has the hooks registered.

This is good advice, thanks.

I guess the one other factor is unit-tests; since these each have their own entry point, you will likely need to import `modelsx` in every applicable package.

> Also FWIW I also use check clauses because I can't be sure that only Go clients will ever talk to the database and at least some basic validation should still be used.

Also a good point, thanks.

-------------------

Entirely separately, I realized that "always-on validation" as a feature would conflict with "acceptance tests" as a feature, since the acceptance tests would have no way to ensure that the structs they're inserting & updating have valid data as per your arbitrary hooks.

So yes, the only viable route is to register them manually, and you've made some good points about how to do that.

**Comment by aarondl** [comment]
> I don't know if that mistake quite merited having init() explained to me slowly and carefully, but I apologize for the confusion.

Take no offense. People of all levels of Go understanding post issues here. Easier to assume no knowledge than to go back and forth filling in blanks.

Glad some of the advice was useful at least.

You are right about the test packages, but in general I find I'm not worried about validation happening there because it's tested properly elsewhere and also it's somewhat assumed the test writer knows how to manipulate the database properly. But it is a valid concern nonetheless. Ideally the same code would be running in both places for parity.
