### ISSUE TITLE
Feature request: Disable foreign-key check to sqlboiler

### ISSUE THREAD

**Issue by bbruun** [volatiletech/sqlboiler#937]
I've been looking for something like this for a long time as I have been trying to re-write an older Rails app to Go and Gorm etc. does not play well with databases and `sqlboiler` seems like a very very cool project that will make the rewrite possible (and future projects where eg Gorm isn't the defining factor for the DB structure). So from what I've seen so far I'm excited.

The application I have has a few tables with more than one foreign key and I would therefore like to ask if there is a way, until hopefully implemented, to get a feature/parameter to `sqlboiler` or option to sqlboiler.toml similar to `blacklist = []` where the format is eg `table.foreignkeyname` where the `foreignkeyname` is ignored when that table is converted to a model?

Eg if `sometable` has 3 foreign keys `sometable.foreignkey_1_name_fkey`, `sometable.foreignkey_2_name_fkey`, and `sometable.foreignkey_3_name_fkey` then 
```
[psql]
  dbname = "existing_db"
  <snip>
  fkeyignore = [ [ "sometable", "foreignkey_2_name_fkey" ], [ "sometable", "foreignkey_3_name_fkey" ] ]
```
Or something similar.

**Comment by aarondl** [comment]
Tables with more than one foreign key isn't a problem for sqlboiler, it works reliably with this. The problem is *composite* foreign keys, meaning foreign keys that are composed of more than 1 column:

```
FOREIGN KEY (b, c) REFERENCES other_table (c1, c2)
```

Currently I'm not interested in supporting a feature that allows you to disable foreign keys as the vast majority of them work and are fine. Composite foreign keys are not that common and I'd rather support them then turn them off. Thanks for filing the issue.
