### ISSUE TITLE
db table name with "_" generates ignored .go file, causing compilation errors

### ISSUE THREAD

**Issue by adonovan** [volatiletech/sqlboiler#944]
I ran sqlboiler on a database containing a table named `_dg_failed_manifest_messages_20210428110417_del`. This caused it to emit a .go file that is ignored by `go build`, presumably because the leading underscore in the .go file name caused it to be interpreted as a build tag. Consequently compilation failed because of missing helper functions such as `whereHelperint64` that happened to be defined in this file.

The code generator should choose file names that are not interpreted as build tags.

**Comment by aarondl** [comment]
Not a build tag, just ignored in compilation because files beginning with `.` and `_` are unlikely to be source files: https://golang.org/pkg/go/build/#Context.Import

To reduce the chance of collisions going to replace a prefixing `_` with `und_` as a special case. This is a fairly arbitrary choice but I feel it's much more likely that someone would have `_table` and `table` than `_table` and `und_table`. I may regret this decision in the future but there also doesn't seem to be any way around it given it must be replaced by something that's not ignored by the Go tool all of which can possibly exist already.

I've added this change and it will end up in a release. Thanks for the report.
