### ISSUE TITLE
cannot convert type: types.NullDecimal Exception

### ISSUE THREAD

**Issue by rtywei** [volatiletech/sqlboiler#969]
The fields of my table are of type "decimal". I use the "sqlboiler mysql" command to generate the structure, and the field type is "types.NullDecimal".

So, 
d := types.NullDecimal{Big: new(decimal.Big)}
	d.Big, _ = d.SetString("2.5")
	//	return reflect.ValueOf(d), nil
	t := models.Test{
		ID:           111,
		UserType:     "11",
		UserName:     null.NewString("David", true),
		FinishRate:   d,
	}
but,
sql execute exception : cannot convert type: types.NullDecimal

**Comment by aarondl** [comment]
Issue template deleted, insufficient information to action this issue.

**Comment by NaitoYuki** [comment]
@rtywei san

I don't know if this is the same cause, but I encountered the same problem.

In my case, the problem was solved by changing the version of ericlagergren/decimal to the same as this library using the following command.

https://github.com/volatiletech/sqlboiler/blob/master/go.mod#L9

```
$ go get github.com/ericlagergren/decimal@v0.0.0-20181231230500-73749d4874d5
go get: downgraded github.com/ericlagergren/decimal v0.0.0-20210307182354-5f8425a47c58 => v0.0.0-20181231230500-73749d4874d5
```

I hope this helps.
